UI Component Button 추가
YAPP-Github/21st-iOS-Team-1-iOS pull request #12
Opened 2022-12-15 08:06 UTC by ungchun

## Motivation
- issue number : #9 

## Screen Shots
![스크린샷](https://user-images.githubusercontent.com/50910456/207803456-66ca7e44-4e26-4daa-8c53-0773f29e43c1.png)

## To Reviewers
- FindTown 줄여서 FTButton으로 만들었습니다..
- 컬러나 자세한 inset 값이나 폰트크기 요런것들은 추후에 확정 및 추가되면 수정하겠습니다!!
- style type 네이밍은 우선 피그마 컴포넌트 제목으로 만들었습니다. (large, xSmall ...)
- 전체적인 네이밍을 신경쓴다고 썼는데.. 피드백 환영입니다!
- FTButton에 setSelectedTitle, setSelectedImage func은 버튼이 클릭했을 때(isSeleted == true) 타이틀이나 이미지가 변경되어야 하는 경우 사용하고 나머지는 기본 UIButton의 setTitle, setImage로 사용합니다!

2022-12-15 11:59 UTC, seonyoung42 reviewed
버튼 종류가 많았는데 벌써 다 하시다니 대박입니당..!! 코드 잘 읽어보았습니다 감사합니다! 첫 코드리뷰 재밌네요 ☺️

2022-12-15 11:59 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
> +        starStackView.addArrangedSubview(star5)
```suggestion

        let starButtons = [star1, star2, star3, star4, star5]
        
        starButtons.forEach {
            starStackView.addArrangedSubview($0)
        }
        
```

요렇게 버튼을 묶어서 작성하는건 어떠세요?... 아래 switch문의 none과 five 케이스에서도 사용할 수 있을 것 같아 제안드려봅니당☺️..!

2022-12-15 18:51 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
> +        starStackView.addArrangedSubview(star5)
오오.. 좋습니다! 최종 수정하고 다시 PR 날리도록 하겠습니다!! :)

2022-12-17 07:17 UTC, llghdud921 requested changes
성훈님~! 고생많으셨습니다 👍

전반적으로 구조 개선을 해보는 것은 어떨까 하고 제안드리려고 하는데요!

현재 구조의 문제점
- `FTButtonStyle`의 프로퍼티가 지나치게 많다고 생각이 들었습니다
- select해도 스타일이 변하지 않는 버튼의 경우에 프로퍼티 낭비가 심하다고 생각이 들었어요

그래서 고민해보았는데요 FTSelectableButton 이라는 버튼을 만들어서 selectStyle을 관리해보면 어떨까 싶어요! FTButton내 코드도 더 간결해지구요! 한번 고려해보셨으면 합니다ㅎㅎ

```
private let selectedButtonStyle: FTButtonStyle
    private let nonSelectedButtonStyle: FTButtonStyle
    
    public init(selectedStyle: FTButtonStyle, nonSelectedStyle: FTButtonStyle) {
        self.selectedButtonStyle = selectedStyle
        self.nonSelectedButtonStyle = nonSelectedStyle
        
        super.init(frame: .zero)
        
        translatesAutoresizingMaskIntoConstraints = false
        changesSelectionAsPrimaryAction = true
        
        configureUI(style: nonSelectedStyle)
    }

required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    public override var isSelected: Bool {
        didSet {
            switch isSelected {
            case true:
                configureUI(style: selectedButtonStyle)
            case false:
                configureUI(style: nonSelectedButtonStyle)
            }
        }
    }
    
   public func setSelectedTitle(normalTitle: String, selectedTitle: String) {
        setTitle(normalTitle, for: .normal)
        setTitle(selectedTitle, for: .selected)
    }
    
    public func setSelectedImage(normalImage: UIImage, selectedImage: UIImage) {
        setImage(normalImage, for: .normal)
        setImage(selectedImage, for: .selected)
    }

```

추가로 궁금하신 점 있으면 DM주세요! 😊

2022-12-17 07:17 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
> +    let configu: UIButton.Configuration
약어는 지양해볼까요☺️

2022-12-17 07:17 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButton.swift
> +        }
테스트를 해보았는데요!

15.5 타겟인 제 시뮬레이터에서 select 해도 스타일이 변하지 않더라구요!
`changesSelectionAsPrimaryAction = true` 아마 해당 프로퍼티를 지정하지 않아서 그렇지 않을까 합니다 😎

2022-12-17 07:17 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButton.swift
> +    public func setSelectedTitle(normalTitle: String = .init(), selectedTitle: String = .init()) {
![스크린샷 2022-12-17 오후 4 09 14](https://user-images.githubusercontent.com/40068674/208230284-555aba3c-8009-4bc9-91a0-85cfb75315cf.png)

init은 사용한 것은 좋은데요! 자동완성을 할 경우 파라미터를 받는 Init이 아래 떠서 약간 불편한 것 같습니다ㅎㅎ

2022-12-17 12:13 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
> +    let configu: UIButton.Configuration
에고.. 조심하겠습니다..! 😢

2022-12-17 12:14 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButton.swift
> +        }
생각없이 16.0으로만 돌려봤네요.. 요부분도 항상 15.~, 16.~ 더블체크 하겠습니다! 👍

2022-12-17 12:17 UTC, ungchun commented
저도 따로 Select Button으로 따로 빼야하나 고민했었는데.. 이렇게 잡아주시니 감사합니다!

2022-12-17 18:08 UTC, llghdud921 requested changes
성훈님 빠른 피드백 감사합니다 👍
제가 리뷰를 너무 늦게 드리는것같아 죄송할따름이네요..ㅠㅠ 차주부터는 빠른 피드백 진행해보겠습니다ㅎㅎ

아래 몇가지 리뷰 남겨놓았어요! 확인부탁드립니다ㅎㅎ

2022-12-17 18:08 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButton.swift
> +        var config = style.configuration
약어를 지양합시다!!

2022-12-17 18:08 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTSelectableButton.swift
> +public final class FTSelectableButton: UIButton {
15.x에서 selected 적용이 안됩니다🤔 위에 말씀드린 프로퍼티 적용하면 될것같네요ㅎㅎ

2022-12-17 18:08 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
> +    public static let mediumBackgroundColorType = FTButtonStyle (
`backgroundColor` 라는 명칭이 통일성도 떨어지고 명확하지 않다고 생각이 드는데요...
fill, tinted, gray와 같은 [configuration](https://developer.apple.com/documentation/uikit/uibutton/configuration) 으로 네이밍을 지어보시는건 어떨까요? ☺️

2022-12-17 18:08 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
> +    public static let largeSelectedType = FTButtonStyle (
모든 FTButtonStyle의 네이밍에 접미사로 Type을 사용하셨는데 Swift의 Struct, Class, Enum 같은 Type과 혼동이 올수도 있을 것같아요!

![스크린샷 2022-12-18 오전 3 06 20](https://user-images.githubusercontent.com/40068674/208255420-d67ad49e-f735-4e07-baa8-9ec942fb9912.png)
UIButton내 Style이 어떻게 네이밍하는지 찾아보았는데 간결하게 사용하네요! type 접미사는 없어도 되지 않을까 생각합니다ㅎㅎ

2022-12-18 07:11 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButton.swift
> +        var config = style.configuration
확인했습니다 ㅠㅠ 😢

2022-12-18 07:14 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTSelectableButton.swift
> +public final class FTSelectableButton: UIButton {
처음에는 changesSelectionAsPrimaryAction = true로 주니까 toggle 효과가 안나타나는 줄 알았는데, tap action에서 또button.isSelected.toggle() 코드가 들어가있었네요.. FTSelectableButton에 changesSelectionAsPrimaryAction = true 추가했습니다!! 15.5, 16.0 으로 확인했는데 한번 더 확인부탁드려요~ 😆

2022-12-18 07:15 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
> +    public static let mediumBackgroundColorType = FTButtonStyle (
아래 type 이랑 같이 나름대로 수정해봤습니다! 😀 네이밍이 참 어렵네요 ㅠㅠ

2022-12-18 07:27 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTSelectableButton.swift
> +public final class FTSelectableButton: UIButton {
radio, Check Button에도 추가했습니다!

2022-12-18 08:00 UTC, llghdud921 requested changes
성훈님 아래 코멘트 남겨두었습니다 :)

2022-12-18 08:00 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/CheckButton.swift
> +        changesSelectionAsPrimaryAction = true
`UIView`의 설정을 하는 코드들이 현재 `init()`에 반복적으로 들어가있는데요 
저희 BaseViewController에 만들어놓은 것처럼 `setupView()`에 정리하는 것은 어떨까요?

2022-12-18 08:00 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/CheckButton.swift
> +public final class CheckButton: UIButton {
저희 `Selectable`이라는 프로토콜을 만들어서 해당 View는 선택가능하다고 명시적으로 알려주면 좋을 것 같은데 어떠신가요? 😀

2022-12-18 08:00 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
> +    }()
이렇게 반복적으로 구현되는 View는 배열로 만들어서 관리하는 것이 좋을 것 같아요 🙂

2022-12-18 08:00 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
> +    }
개인적인 의견이지만 `StarType`이라는 네이밍보다는 `Importace`나 `Priority`와 같은 중요도를 나타내는 네이밍이 적합할 것 같아요 
case 네이밍도 또한 개선 가능할 것 같습니다 :)

2022-12-18 11:42 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
> +    private let rattingGuirdTitle: UILabel = {
오타발견!

2022-12-18 17:02 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
> +    }
네이밍 StarPriorty 로 수정했고, enum 네이밍도 low, medium, high 로 수정했습니다 !!😀
훨씬 좋아보이네요! 감사합니다!! 👍

2022-12-18 17:02 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
> +    private let rattingGuirdTitle: UILabel = {
하핫..

2022-12-18 17:02 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
> +    }()
왜 이런 생각은 코드 작성할 때는 생각나지 않을까요 ㅠㅠ

2022-12-18 17:02 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/CheckButton.swift
> +public final class CheckButton: UIButton {
오오.. 한번도 해보지 않은 스타일이라 Selectable 요런 느낌을 생각하신게 맞을까요?? 😅

2022-12-18 17:05 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/Button/CheckButton.swift
> +        changesSelectionAsPrimaryAction = true
Base로 만들어서 빼보려 했는데 뭔가 더 복잡해지는거 같고 생각대로 잘 나오지 않더라구요.. 
결국 seletedButton은 두줄, nonSeletedButton은 한줄 추가 되는데 요 부분은 그냥 진행해도 괜찮지 않을까요..?? 😢

2022-12-19 02:41 UTC, llghdud921 approved these changes
👍👍

2022-12-19 04:03 UTC, seonyoung42 approved these changes
고생많으셨습니다 ☺️!!

2022-12-19 10:38 UTC, merged