UI Component 중 Font, Color 추가
YAPP-Github/21st-iOS-Team-1-iOS pull request #13
Opened 2022-12-16 09:29 UTC by seonyoung42

## Motivation
- issue number : #9

## Changes
- 디자인 시스템의 Custom Font와 Custom Color 추가한 후 Extension으로 UIFont와 UIColor 위치에서 바로 사용할 수 있도록 하였습니다.
- FindTownUI Package에 있는 Font와 Color 리소스들을 FindTown 프로젝트에서 적용할 수 있도록 하였습니다.

## To Reviewers
Font 등록을 위해서 FindTown 프로젝트의 Appdelegate에서 registerFont() 함수를 호출하도록하였는데 혹시 더 적당한 위치가 있을 것 같다면 조언 부탁드립니다.. 핳

2022-12-17 03:41 UTC, ungchun commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +}
고생하셨습니다! 폰트랑 컬러가 한눈에 잘보이네요😀
앱 시작할 때 폰트를 등록해야하면 AppDelegate 괜찮아 보이네요! 😀
한가지 궁금한게 registerFonts() 호출하는 AppDelegate 코드가 안보이는데, 깃에서 추적이 안된걸까요..? 🤔

2022-12-17 07:20 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +}
헉 UI 패키지 파일만 올렸어요...😱 APP 프로젝트 파일도 함께 올려서 다시 PR 날리겠습니다..!!

2022-12-17 12:32 UTC, ungchun approved these changes
고생하셨습니다!! 😀

2022-12-17 18:49 UTC, llghdud921 requested changes
선영님 고생많으셨습니다!!
리뷰 너무 늦게드려서 죄송해요..😭

2022-12-17 18:49 UTC, llghdud921 commented on FindTown/FindTown/Application/AppDelegate.swift
> +        registerFonts()
오.. AppDelegate내에서 CustomFont를 등록하는 것을 처음 알았어요!

저는 기존에 [addingacustomfonttoyourapp](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app) 에 나와있는 것처럼 info.plist에 추가를 해주었는데요! 
![스크린샷 2022-12-18 오전 3 26 15](https://user-images.githubusercontent.com/40068674/208256117-28b0d1c9-4aa6-4e84-b41f-b1a49c03094b.png)
비교해보고 선영님이 더 적절하다고 생각하는 방식으로 진행해주시면 될 것 같습니다!

2022-12-17 18:49 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/UIColor+Extension.swift
> +    static let back1: UIColor = .init(named: "Back1", in: .module, compatibleWith: nil) ?? .clear
```suggestion
    static let back1 = UIColor(named: "Back") ?? .clear
```
`init` 메서드를 안쓰면 조금 더 코드가 간결해질 것 같아요!

2022-12-17 18:49 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +    static let H3: UIFont = .init(name: "Pretendard-SemiBold", size: 24.0) ?? .systemFont(ofSize: 24.0)
네이밍이 H1, H2, H3 이렇게 피그마에도 나와있는데 명확성을 위해서 headline1, headline2, headline3 이런식으로 네이밍을 해보는게 어떠할지 조심스럽게 제안드려봅니다ㅎㅎ

그리고 아래 코드처럼 Enum을 활용해서 코드를 구성해볼수도 있을 것 같아요!
```
enum TextStyle {
    case H1
    case H2
    case H3
    case S1
    case S2
    case B1
    case B2
}
```

2022-12-17 18:49 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +    static let H1: UIFont = .init(name: "Pretendard-SemiBold", size: 32.0) ?? .systemFont(ofSize: 32.0)
Nil Coalescing Operator를 반복적으로 사용하게 되는데 아래와 같은 코드로 개선해볼 수 있지 않을까 생각해봅니다!  ☺️

```
extension UIFont {
    class func Pretendard(type: PretendardType, size: CGFloat) -> UIFont {
        guard let font = UIFont(name: type.name, size: size) else { return UIFont.systemFont(ofSize: size) }
        return font
    }

    public enum PretendardType {
        case regular
        case medium
        case semiBold
        case light

        var name: String {
            switch self {
            case .regular:
                return "Pretendard-Regular"
            case .medium:
                return "Pretendard-Medium"
            case .semiBold:
                return "Pretendard-SemiBold"
            case .light:
                return "Pretendard-Light"
            }
        }
    }
}
```

2022-12-18 08:19 UTC, seonyoung42 commented on FindTown/FindTown/Application/AppDelegate.swift
> +        registerFonts()
맞아요! 저도 기존에는 info.plist 에서 폰트를 등록했었는데 이번에는 폰트파일(.otf) 이 앱 프로젝트 파일이 아닌 UI 패키지에 들어 있어서 그런지 info.plist에서 등록해도 폰트 적용이 되지 않더라구요..🥵 
그래서 UI 패키지에 폰트 적용 메소드(=> registerFonts())를 작성해놓고 그 메소드를 앱 프로젝트 파일에서 호출하도록 해놓았습니다..! 

그럼 폰트 적용 메소드 호출 시점은 그대로 유지하도록 하겠습니당..!

2022-12-18 08:24 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/UIColor+Extension.swift
> +    static let back1: UIColor = .init(named: "Back1", in: .module, compatibleWith: nil) ?? .clear
앗 확실히 그렇네요 !! 수정하겠습니다 !!

2022-12-18 08:37 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +    static let H3: UIFont = .init(name: "Pretendard-SemiBold", size: 24.0) ?? .systemFont(ofSize: 24.0)
아 저도 폰트 네이밍이 조금 마음에 걸렸어요..!! 그런데 피그마상에서 다른 UI 컴포넌트들을 눌렀을 때 폰트정보가 H1, H2 이렇게만 보이기에 피그마와 네이밍이 통일되는게 더 우선일 것이라 판단해서 이렇게 설정했습니다 😰

제 생각에는 
1. headLine1이라는 네이밍을 쓰되 headLine1 = H1 이라고 Xcode 상에 주석으로 작성
2. 디자이너 분께 폰트 네이밍 수정 요청
요렇게 두 가지 방안이 있을 것 같은데 의견이 궁금합니당..!!

2022-12-18 08:39 UTC, llghdud921 commented on FindTown/FindTown/Application/AppDelegate.swift
> +        registerFonts()
오!!! 그렇군요 제가 잘 몰랐습니다ㅠㅠㅠ 지금 호출시점 좋은 것 같아요 👍

2022-12-18 08:40 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +    static let H1: UIFont = .init(name: "Pretendard-SemiBold", size: 32.0) ?? .systemFont(ofSize: 32.0)
대박적 너무 좋은 방법이에요.. 적용하니 코드가 훨씬 깔끔해졌습니다..!! 감사해요 ☺️!!

2022-12-18 08:41 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +    static let H3: UIFont = .init(name: "Pretendard-SemiBold", size: 24.0) ?? .systemFont(ofSize: 24.0)
흐음..... 코드 상으로 headLine으로 명시하는 것이 더 좋을 것 같아서 
디자이너분께 폰트 네이밍 수정요청을 해보는게 좋지 않을까 합니다ㅎㅎ

2022-12-18 11:04 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +    static let H3: UIFont = .init(name: "Pretendard-SemiBold", size: 24.0) ?? .systemFont(ofSize: 24.0)
디자이너분께서 수정해주신다고 하셔서 풀어쓴 네이밍으로 수정하겠습니다 ☺️!

그리고 제안해주신 enum으로 폰트를 지정하는 방법에 대해서 궁금한게 있는데요..!!
```
public extension UIFont {
    
    enum TextStyle {
        case headLine1
        case headLine2
        case headLine3
        
        public var font: UIFont {
            switch self {
            case .headLine1:
                return UIFont.pretendard(type: .semiBold, size: 32.0)
            case .headLine2:
                return UIFont.pretendard(type: .semiBold, size: 28.0)
            case .headLine3:
                return UIFont.pretendard(type: .semiBold, size: 24.0)
            }
        }
    }

```
다음과 같이 작성하고 사용할 때는 아래와 같이 사용하는 걸 말씀하신게 맞을까요?!

```
label.font = .TextStyle.headLine1.font
```
기존 방법보다 확실히 개발자가 제공하는 TextStyle들을 한 번에 보기 편리해서 관리하기에는 정말 좋을 것 같은데요..!! 다만 기존 방법(label.font = .headLine)에 비해 사용할 때 조금은 불편하다는 생각도 들어서요 ㅠㅠ 혹은 enum을 사용해서 다르게 코드를 짤 수도 있는 걸까요?..

2022-12-18 14:07 UTC, seonyoung42 commented
Extension에서 Font와 Color를 설정했던 기존의 방식에서 아예 enum으로 FindTownColor와 FindTownFont를 정의하도록 변경하였습니다 ! 

해당 리소스들을 사용할 때에 작성해야하는 코드가 늘어났다는 단점이 있지만 커스텀 리소스를 관리하기 쉽다는 장점이 더 크다고 판단해서 이와 같이 수정해보았습니다..! 그러나 자주 사용되는 리소스인 만큼 모두의 의견이 다 반영되어야한다고 생각해서 수정된 부분 한 번 보시고 피드백 부탁드립니다 ☺️!!

```
// 기존 방식
view.backgroundColor = .primary 
label.font = .headLine1

// 변경된 방식
view.backgroundColor = FindTownColor.primary.color
label.font = FindTownFont.headLine1.font
```

2022-12-18 14:07 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/UIFont+Extension.swift
> +    static let H3: UIFont = .init(name: "Pretendard-SemiBold", size: 24.0) ?? .systemFont(ofSize: 24.0)
거의 비슷하긴 한데요!! 제가 말한건 아래처럼 코드를 작성하는 거였어요! (.TextStyle이 아닙니당...😅)
```
label.font = TextStyle.headLine1.font
```

2022-12-18 14:28 UTC, llghdud921 approved these changes
너무 좋습니다 👍

2022-12-19 10:37 UTC, ungchun approved these changes
아이고.. 재검토 요청 메일을 착각을 해서 확인을 못했네요ㅠㅠ.. 다음부터는 주의하겠습니다! 고생하셨습니다!!👍

2022-12-20 00:25 UTC, merged