BaseBottomSheetViewController 추가
YAPP-Github/21st-iOS-Team-1-iOS pull request #14
Opened 2022-12-16 09:42 UTC by ungchun

## Motivation
- issue number :  #9 

## Screen Shots 
<img width="496" alt="스크린샷 2022-12-16 오후 6 32 38" src="https://user-images.githubusercontent.com/50910456/208068125-77f0f54d-a970-4b41-bfaa-93acf6360f17.png">

![Simulator Screen Recording - iPhone 14 - 2022-12-16 at 18 30 58](https://user-images.githubusercontent.com/50910456/208067846-efbe6e4f-1946-4648-88cf-8ab62e724729.gif)

## To Reviewers
- BaseBottomSheetViewController를 상속받아서 바텀시트를 만들고 modal fullScreen으로 띄웁니다.
- 바텀시트를 bottomHeight 만큼 보이게 합니다. ( 바텀시트 높이가 정해지면 수정하겠습니다 :) )
- 상속받아서 쓰는 거라 이름도 Base붙이고, Common - ViewController 에 넣어놨는데 의견주시면 감사하겠습니다!! 😀

2022-12-16 10:07 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/Common/ViewController/BaseBottomSheetViewController.swift
> +
```suggestion
    enum BottomSheetStatus {
        case show
        case hide
    }
    
    private func setBottomSheetStatus(to status: BottomSheetStatus) {
        let safeAreaHeight: CGFloat = view.safeAreaLayoutGuide.layoutFrame.height
        let bottomPadding: CGFloat = view.safeAreaInsets.bottom
        
        switch state {
        case .show: 
            bottomSheetViewTopConstraint.constant = (safeAreaHeight + bottomPadding) - bottomHeight
        case .hide: 
           bottomSheetViewTopConstraint.constant = safeAreaHeight + bottomPadding
        }
        
        UIView.animate(withDuration: 0.25, delay: 0, options: .curveEaseIn, animations: {
            self.dimmedBackView.alpha = 0.0
            self.view.layoutIfNeeded()
        }) { _ in
            if self.presentingViewController != nil {
                self.dismiss(animated: false, completion: nil)
            }
         }
      }
    
```

2022-12-16 10:11 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/Common/ViewController/BaseBottomSheetViewController.swift
> +        hideBottomSheet()
```suggestion
        setButtonSheetStatus(to: .hide)
```
setButtonSheetStatus() 메소드를 쓴다면 이렇게 호출할 수 있을 것 같습니당..!

2022-12-16 10:16 UTC, seonyoung42 reviewed
성훈님 너무 열.코딩러 아니냐면서,, 덕분에 저희 프로젝트가 완전 기대가 됩니당..!! 오늘도 코드 잘 읽었습니다 감사합니다 ! ☺️


추가로 궁금한 점인데 혹시 SnapKit을 안쓰시는 이유가 있을까용?! 저는 translatesAutoresizing.. = false를 명시하지 않아도 되고, 여러모로 코드를 줄일 수 있어서 코드로 UI 짤 때 유용하게 사용했었거든요..!

2022-12-17 03:44 UTC, ungchun commented on FindTown/FindTown/Presentation/Common/ViewController/BaseBottomSheetViewController.swift
> +
오오.. 훨씬 좋은 거 같아요! 수정해서 다시 올릴게요! 👍

2022-12-17 03:46 UTC, ungchun commented
아이고.. 아닙니다..
그 Snapkit은 저번에 세션할 때 호영님이랑 이야기했는데, 최대한 라이브러리 한쓰고 프로젝트를 진행하기로 했습니다. 그래서 Snapkit도 사용안하기로 했어요! 미리 말씀드려야 했었는데, 죄송합니다ㅠ

2022-12-17 19:37 UTC, llghdud921 requested changes
성훈님 고생많으셨습니다!

꼭 필요한 것은 아니지만 시간이 괜찮으시다면 지난번에 이야기하셨던 드래그로 올리고 내리는 바텀시트를 구현해보는것은 어떠할지 여쭤봅니다😊 
아무래도 dismissIndicatorView가 있는데 expand가 되지 않으면 이상하다고 느껴질수도 있으니까요!
만약 구현하신다면 라이브러리를 사용하지 않고 직접 구현하는 방향으로 진행해보셨으면 합니다ㅎㅎ

2022-12-17 19:37 UTC, llghdud921 commented on FindTown/FindTown/Presentation/Common/ViewController/BaseBottomSheetViewController.swift
> +    private let bottomHeight: CGFloat = 360
`BaseBottomSheetViewController`를 상속받았는데 bottomHeight 크기를 다르게 지정하고 싶으면 어떻게 해야하나요? 🙂

2022-12-19 06:34 UTC, ungchun commented on FindTown/FindTown/Presentation/Common/ViewController/BaseBottomSheetViewController.swift
> +    private let bottomHeight: CGFloat = 360
height값은 고정일거라는 생각만했네요.. 😭
바텀시트를 생성할 때 height값을 받는쪽으로 수정했습니다!

2022-12-19 06:45 UTC, ungchun commented
드래그로 올리고 내리는 바텀시트를 고민해 봤는데요..!

![Group 28](https://user-images.githubusercontent.com/50910456/208363389-e2b1d7ff-fe61-4f80-9073-7b63cf46f959.png)  

예전에 피그마에서 테마지도를 보면 왼쪽처럼 올리고 내리는 바텀시트가 들어가 있었는데 최근에 거의 픽스된 뷰를 보면 오른쪽처럼 돼있더라구요! 현재까지 올리고 내리는 바텀시트가 필요없는 거 같아서 나중에 필요해지게 되면 구현해보는 쪽으로 가도 괜찮지 않을까..? 조심히 말해봅니당.. 😅

2022-12-19 10:21 UTC, seonyoung42 approved these changes

2022-12-19 10:23 UTC, seonyoung42 commented
수정된 부분 확인했습니다 고생많으셨어요 ☺️!! 
옹 저는 바텀시트 확실히 필요해지면 만들어도 괜찮을 것 같아요 !!

2022-12-28 14:13 UTC, llghdud921 approved these changes
성훈님 이거 approve 한줄알았는데 안했네요..... 🥲
다음부터는 잘 살피겠습니다 🙇‍♀️

2022-12-28 14:59 UTC, closed without merging