UI Component 중 Switch, Label, TextField 구현
YAPP-Github/21st-iOS-Team-1-iOS pull request #25
Opened 2022-12-20 12:58 UTC by seonyoung42

## Motivation
- issue number : #9 

## Changes
- 동네지도에서 사용되는 인프라, 테마 지도 전환 토글 스위치(MapSwitch) 구현
- FindTownLabel 구현 
- FindTownTextField 구현

## Screen Shots

### Map Switch
￼![이미지 2022  12  20  오후 9 43](https://user-images.githubusercontent.com/77603632/208670381-b7da11bb-bc3b-4d98-aa39-f5f0a3391377.jpg)

#### Map Switch 적용 방법
```
let mapSwitch = MapSwitch(items: ["인프라", "테마"])
view.addSubview(mapSwitch)
```

### FindTownLabel

![이미지 2022  12  20  오후 10 35](https://user-images.githubusercontent.com/77603632/208679632-0e9df460-a4a3-4309-91e5-34f7fce6a6b7.jpg)

#### FindTownLabel 적용 방법
```
let townLabel = FindTownLabel(text: "test", font: .headLine1, textColor: .black, textAlignment: .left)
//let townLabel = FindTownLabel(text: "test", font: .headLine1)로도 작성 가능
view.addSubview(townLabel)

```

### FindTownTextField
![ezgif com-gif-maker](https://user-images.githubusercontent.com/77603632/208891277-c2a2f4b4-b4e5-4fd1-80b8-25b5b670e84d.gif)

#### FindTownTextField 사용 방법

```
let textF = FindTownTextField()
textF.placeholder = "textField test textField test textField test te"
view.addSubview(textF)
```

## To Reviewers
### - MapKit
+ UISegmentControl로 구현했지만 피그마에 토글 스위치라 기재되어 있어 MapSwitch 로 네이밍 했는데 SegmentControl을 사용해서 네이밍 해야했을지 고민이 됩니다 🥹
### - FindTownLabel
+ FindTownLabel의 textColor = black, textAlignment = left로 default 설정해놓았는데 혹시 어떤가요?
+ FindTownLabel에 더 추가되었으면 하는 설정있으면 말씀해 주세요 !!
    + 개발하면서 필요한게 있으면 더 추가할 예정이긴 합니다.!
### - FindTownTextField
+ 피그마에 아직까지는 clearButton의 유무만 차이가 있기에 init할 때 clearButtonMode를 설정할 수 있도록 하였습니다
    +  FindTownTextField도 clearButtonMode = .whileEditing로 default 설정을 넣어놨는데 어떤가요?
+ TextField layer 색상이 status(작성 중, 작성 중 아님, 텍스트가 조건을 만족하지 않음)에 따라 바뀌는데 status 바꾸는 설정을 어디서 할 지 고민입니다. 
  + status(작성 중, 작성 중 아님) 만 있는 경우
       + FindTownTextField.swift 내에 setTextFieldStatus()메서드가 있어 따로 설정 필요 없음
  + status(작성 중, 작성 중 아님, 텍스트가 조건을 만족하지 않음) 모두 다 있는 경우 <- 가 고민입니다 🥵
       + 선택1) FindTownTextField.swift에 "텍스트가 조건을 만족하지 않음" 인 경우를 외부에서 받을 수 있는 변수 넣어주기
              + 장점 : status(작성 중, 작성 중 아님) 일 때 계속 setTextFieldStatus() 사용할 수 있음
              + 단점 : 코드가 지저분해짐
       + 선택2) 모든 status 설정을 외부에서 하도록
              + 장점 : 코드 깔끔 
              + 단점 : TextFieldDelegate 사용해야함, status(작성 중, 작성 중 아님)인 경우에도 status 설정을 외부에서 해야함(=> setTextFieldStatus() 사용할 수 없음)

### - 그 외
+ component들 속성 설정 메서드 네이밍 BaseViewController와 통일하는거 어떠신가용? 
   + 지금은 성훈님께서 사용하신 네이밍(configureUI()) 사용했는데 BaseVC에는 setupView()로 되어있더라구요..!

2022-12-22 08:15 UTC, llghdud921 requested changes
선영님!! 너무너무 좋아요!! ☺️ 
고생많으셨습니다 

- MapSwitch 네이밍
   저는 SegmentControl로 네이밍하는 것이 개발하는 데 혼동이 오지 않을 것 같아요!
   UISwitch 또한 존재하니까요 ㅎㅎ 저도 잘은 모르지만 안드로이드, 디자인, 웹이 같은 뷰를 다르게 명칭하는 일을 많이 보았어요! 그래서 뷰의 네이밍 기준은 저희 ios 명칭을 따르는게 명확하지 않을까 싶습니다!
   
- FindTownLabel,  FindTownTextField 기본값
    지금 설정되어 있는 기본값 너무 좋습니다👍
    
- FindTownTextField status
    저는 status(작성 중, 작성 중 아님, 텍스트가 조건을 만족하지 않음)다 설정해놓고 rxCocoa로 바인딩해서 해당 status를 바꿔줄 계획이었습니다!
    제가 잘 이해한건지.. 모르겠는데 이것이 아니라면 DM으로 다시 말씀해주세요!!
    
- 그 외
   setupView()나 configureUI() 어떤것을 사용할지 또 고민되는 것이 FindTownView, FTView 이렇게 네이밍해야하나 생각이 드는데요 다음 회의때 다같이 논의해볼까요?
   
- 추가 의견
   현재 선영님이 만들어주신 View들이 FindTownUI에 있는데 label/FindTownLabel 이렇게 각 폴더에 두는것은 어떠세요? 또다른 label이 생길수도 있다고 생각이 듭니다! 😃

2022-12-22 08:15 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/FindTownLabel.swift
> +        self.textAlignment = textAlignment
요 코드들은 선영님이 제안하신 `setupView()` 에 넣어도 좋을 것 같아요!

2022-12-22 08:15 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/MapSwitch.swift
> +    func removeDivider() {
궁금한 점이 있습니다🙋‍♀️ 제 시뮬레이터에서는 해당 메소드가 없어도 동일하게 보이는 것 같은데..
어떤것이 변경되는 걸까요?

2022-12-22 16:09 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/FindTownLabel.swift
> +        self.textAlignment = textAlignment
```

public init(text: String,
            font: FindTownFont,
            textColor: FindTownColor = .black,
            textAlignment: NSTextAlignment = .left) {
                    
    super.init(frame: .zero)
    translatesAutoresizingMaskIntoConstraints = false
        
    self.setupView(text: text,
                   font: font,
                   textColor: textColor,
                   textAlignment: textAlignment)
        
 }

func setupView(text: String,
               font: FindTownFont,
               textColor: FindTownColor,
               textAlignment: NSTextAlignment) {
        
    self.font = font.font     
    self.textColor = textColor.color
    self.text = text
    self.textAlignment = textAlignment
}
```
이거 말씀하시는게 맞을까요?! 설정해주는 값들이 전부 init할 때 파라미터로 받는 값들이라 메서드로 빼지 않았었어요..! 그래도 메서드로 빼니까 좀 더 깔끔하게 보이네용 ☺️

2022-12-22 16:10 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/MapSwitch.swift
> +    func removeDivider() {
앗 제가 여러가지 방법을 시도했었다보니 구분선 제거 코드가 중복으로 들어가 있었어요 😱 삭제하겠습니다 !!

2022-12-22 16:46 UTC, seonyoung42 commented
> * FindTownTextField status
>   저는 status(작성 중, 작성 중 아님, 텍스트가 조건을 만족하지 않음)다 설정해놓고 rxCocoa로 바인딩해서 해당 status를 바꿔줄 계획이었습니다!
>   제가 잘 이해한건지.. 모르겠는데 이것이 아니라면 DM으로 다시 말씀해주세요!!

아 호영님이 이해하신게 맞습니다 !! 
그런데 해당 방법을 사용하면 FindTownTextField 내부 메서드(setTextFieldStatus())를 사용할 수 없다는게 문제입니다 ㅠㅠ
status(작성 중, 작성 중 아님)인 경우에는 setTextFieldStatus()를 사용하면 외부에서 추가 설정 하지 않아도 status를 알아서 바꿔주기때문에 가능하면 해당 메서드를 사용하고 싶어서요 🥺

음.. 지금 생각으로는 init 파라미터로 "텍스트가 조건을 만족하지 않음"의 포함 여부를 구분할 수 있게 하고 이에 따라 setTextFieldStatus()를 사용하도록 하는 방법이 떠오르는데.. 어떨지 모르겠네요 🥹 일단은 이렇게 수정해볼게요 한 번 검토 부탁드려용..!!

그외 다른 부분들은 말씀해주신 부분들 반영해서 수정하겠습니다 자세한 리뷰 감사합니다 ☺️!!!

2022-12-23 03:46 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/FindTownLabel.swift
> +        self.textAlignment = textAlignment
어머! 그러네요ㅎㅎ init 파라미터로 받는 값이라고 생각을 못했습니다ㅎㅎ
선영님이 괜찮으시다고 생각하시는 방식으로 구현해주시면 될 것 같아요!

2022-12-23 04:50 UTC, llghdud921 requested changes
선영님 반영해주신것 잘 보았습니다!!
아래 코멘트 확인 부탁드릴게요 😀

2022-12-23 04:50 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/FindTownColor.swift
> +        case .semantic:
asset에 sementic color가 없는데... 저한테만 안보이는 걸까요?ㅠㅠ
<img width="159" alt="스크린샷 2022-12-23 오후 1 40 22" src="https://user-images.githubusercontent.com/40068674/209272078-0c1f0073-5be5-4af1-b05d-a9e3b4dad179.png">

2022-12-23 04:50 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/FindTownTextField.swift
> +    }
혹시 에러처리를 테스트해보셨을까요? 전 상태가 바로 반영이 되지 않아서..🥲 layoutIfNeeded를 추가했을때 반영이 되었어요!

```suggestion
    public var status: FindTownTextFieldStatus = .unfocused {
        didSet {
            switch status {
            case .unfocused:
                self.layer.borderColor = FindTownColor.grey4.color.cgColor
            case .error:
                self.layer.borderColor = FindTownColor.semantic.color.cgColor
            case .focused:
                self.layer.borderColor = FindTownColor.grey6.color.cgColor
            }
            self.layoutIfNeeded()
        }
    }
```

2022-12-23 06:02 UTC, ungchun reviewed
선영님! 고생하셨습니다!! 😀
리뷰가 늦어서 죄송합니다 ㅠㅠ 어제까지 완성해보겠다고 말씀드렸는데.. 오늘까지 최대한 끝내보겠습니다ㅠㅠ

- MapKit
SegmentControl로 이미 수정해놓으셨네요!! 👍

- FindTownLabel
기본값 이대로 가고 나중에 필요하다면 그때 넣어도 충분할 거 같습니다!! 👍👍

- FindTownTextField
```
/// ViewController
textF.rx.text
    .bind { [weak self] in
        if $0!.count > 5 {
            self?.textF.status = .error
        } else {
            self?.textF.status = .focused
        }
    }
    .disposed(by: disposeBag)

/// FindTownTextField
func setTextFieldStatus() {
    if self.isFirstResponder && self.status != .error {
        self.status = .focused
    } else if self.isFirstResponder && self.status == .error {
        self.status = .error
    } else {
        self.status = .unfocused
    }
}
```
isFirstResponder 이런 값도 있었다니.. 😀
제가 완벽하게 이해하지는 못했지만.. 이런 느낌으로 접근하면 status(작성 중, 작성 중 아님, 텍스트가 조건을 만족하지 않음 + setTextFieldStatus 사용이 가능하지 않을까.. 생각을 해봤습니다..!
아 물론 제가 정답은 아닙니다.. ㅎㅎㅎ;;

아 그리고 text를 끝까지 작성했을 때 clear 버튼을 덮어버리더라구요! 물론 길이 제한을 두고 이것저것 처리를 하겠지만.. 혹시나 싶어서 작성했습니다!
한번 확인 부탁드릴게요~ 😀😀 
<img width="283" alt="스크린샷 2022-12-23 오후 2 57 37" src="https://user-images.githubusercontent.com/50910456/209280027-d1877e68-4302-4674-88e9-78041959d87a.png">

- 그 외
호영님이 말씀해주신 setupView()나 configureUI() + FindTownView, FTView 요 부분 다음 회의 때 정해봅시다!! 😀

2022-12-23 07:20 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/FindTownColor.swift
> +        case .semantic:
😱 Asset 파일을 푸쉬를 안했네요.. 😱 추가하겠습니다 !!

2022-12-23 07:22 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/FindTownLabel.swift
> +        self.textAlignment = textAlignment
수정하고 보니 다른 컴포넌트들은 파라미터로 받는 값들은 따로 메서드로 빼지 않았더라구요..! 통일하는게 좋을 것 같아서 다시 원래대로 바꾸려고 합니당..!! 핳☺️☺️

2022-12-23 07:37 UTC, seonyoung42 commented
> * FindTownTextField
>```
> /// ViewController
>textF.rx.text
>    .bind { [weak self] in
>        if $0!.count > 5 {
>            self?.textF.isError = true
>        } else {
>            self?.textF.isError = false
>        }
>    }
>    .disposed(by: disposeBag)
>
>```
>```
> /// FindTownTextField
> func setTextFieldStatus() {
>     if self.isFirstResponder && self.isError {
>         self.status = .error
>     } else if self.isFirstResponder && self.isError == false {
>         self.status = .focused
>     } else {
>         self.status = .unfocused
>     }
> }
> ```

성훈님 제안주신 방법 넘 좋아요 🤩!! init 파라미터로 isErrorCaseIncluded 를 받지 않아도 되고, setTextFieldStatus() 메서드 하나로 두 가지 케이스에 모두 적용이 가능하네요 !! 다만 status의 설정이 중복이 되고 있어서 isError를 변수를 사용하는 것으로 수정해보았습니다..!!

> 아 그리고 text를 끝까지 작성했을 때 clear 버튼을 덮어버리더라구요! 물론 길이 제한을 두고 이것저것 처리를 하겠지만.. 혹시나 싶어서 작성했습니다! 한번 확인 부탁드릴게요~ 😀😀 <img alt="스크린샷 2022-12-23 오후 2 57 37" width="283" src="https://user-images.githubusercontent.com/50910456/209280027-d1877e68-4302-4674-88e9-78041959d87a.png">
> 
이 부분 완전 놓치고 있었네요 🥵 수정했습니다 확인해주셔서 감사합니다 !!

2022-12-24 02:25 UTC, llghdud921 approved these changes
고생하셨습니다😀

2022-12-24 03:26 UTC, ungchun approved these changes
고생많으셨습니다!! 👍

2022-12-24 11:27 UTC, merged