BaseNavigationController, BaseTabBarController 추가
YAPP-Github/21st-iOS-Team-1-iOS pull request #26
Opened 2022-12-24 10:46 UTC by llghdud921

## Motivation
- issue number :  #17 

## Changes
- BaseNavigationController 추가 및 NavigationBar 관련 속성 설정
- BaseTabBarController 추가 및 TabBar 관련 속성 설정

## Screen Shot
<img width="373" alt="스크린샷 2022-12-24 오후 7 45 23" src="https://user-images.githubusercontent.com/40068674/209432470-d28df067-8a2e-4961-ae0f-4ba95fa57015.png">

## To Reviewers
icon을 추가하기 전이라서 system icon 사용해서 넣었습니다~!

2022-12-24 14:54 UTC, ungchun commented on FindTown/FindTownCore/Sources/FindTownCore/Base/BaseNavigationController.swift
> +
```suggestion
open class BaseNavigationController: UINavigationController {

    open override func viewDidLoad() {
        super.viewDidLoad()

```
![스크린샷 2022-12-24 오후 11 53 30](https://user-images.githubusercontent.com/50910456/209441479-d19e40fa-0c20-45e6-9574-1a010d7e96a5.png)

public 으로 하면 오버라이드와 서브클래싱이 안돼서 요부분 open 으로 수정해야 할 거 같아요! 😎

2022-12-24 15:04 UTC, ungchun reviewed
호영님! 이브날인데.. 고생하셨습니다!! 👍

- BaseTabBarController에 Font 관련 세팅은 안보이는데, VC에서 따로 세팅하는 쪽으로 생각하신건가요..?!
- 제 능력부족으로.. BaseNavigationController는 어떻게 테스트해야할지 모르겠더라구요 ㅎㅎㅎ;; 혹시 서브클래싱이나 오버라이드를 사용한다면 요것도 public 말고 open 으로 수정해야 할 거 같습니다!! 한번 확인 부탁드릴게요~ 😀

2022-12-24 19:12 UTC, llghdud921 commented on FindTown/FindTownCore/Sources/FindTownCore/Base/BaseNavigationController.swift
> +
서브클래싱하는 목적이 아니라서 public으로 두었어요!

TabBarController, NavigationController내 appearance를 지정하기 위한 클래스에요 ☺️

2022-12-24 19:32 UTC, llghdud921 reviewed
성훈님!
BaseNavigationController와 BaseTabBarController는 appearance 설정 중복 코드를 줄이려고 UInavigationController 대신 사용하기 위함으로 만든거였어요! 
그래서 서브클래싱이 필요하지 않다고 판단하였습니다

- font설정 빼먹은거 추가하였습니다! 감사합니다~!

2022-12-25 05:09 UTC, ungchun approved these changes
방금 이것저것 해보니 서브클래싱 안하고도 가능하군요!!! 
좋아요! 하나 배워갑니다..!! 👍
고생하셨습니다! 크리스마스 잘 보내세요~~ 🎁

2022-12-25 10:27 UTC, seonyoung42 commented
호영님 고생많으셨어요 !!
지금 설정된 부분들 다 좋아요 👍🏻 !!
그런데 BaseTabBar 상단이 피그마랑 조금 다른 것처럼 보이는데 저만 그런걸까요?.. 피그마에는 회색 border 라인인데 시뮬레이터로는 그림자로 보여서요 🥲🥲

2022-12-25 15:26 UTC, llghdud921 reviewed
TabBarborder가 있었네요! 없는줄 알았어요ㅎㅎ
제가 꼼꼼하지 못해서.. 꼼꼼하게 봐주셔서 너무 감사드립니다!!

2022-12-26 07:07 UTC, seonyoung42 requested changes

2022-12-26 07:07 UTC, seonyoung42 commented on FindTown/FindTownCore/Sources/FindTownCore/Base/BaseTabBarController.swift
> +
```
func addTopBorder() {
        let topBorder = CALayer()
        topBorder.frame = CoreGraphics.CGRect(x: 0, y: 0, width: self.tabBar.bounds.width, height: 1)
        topBorder.backgroundColor = FindTownColor.grey3.color.cgColor
        tabBar.layer.addSublayer(topBorder)
    }
```
호영님 텝바 상단 보더를 shadow 색상으로만 처리해놓으신 것 같은데 CALayer로 추가하는건 어떠실까요?.. 피그마에 구현된 텝바 보더보다 두께가 조금 얇은 것 같아 제안드려봅니당..☺️

2022-12-26 07:15 UTC, seonyoung42 commented
+ 피그마
<img width="587" alt="스크린샷 2022-12-26 오후 4 10 36" src="https://user-images.githubusercontent.com/77603632/209516376-5aa547ff-41fc-4fbe-b8aa-b647ea41cb76.png">

+ 기존 탭바 
![이미지 2022  12  26  오후 4 09](https://user-images.githubusercontent.com/77603632/209516226-b97ef286-deab-43b7-80f2-ddfd9fe5d8f0.jpg)

+ addTopBorder() 추가
![이미지 2022  12  26  오후 4 09 (1)](https://user-images.githubusercontent.com/77603632/209516231-266d81b7-d496-4566-addb-97926af6e847.jpg)

호영님 상단 borderline 추가해주신 것 확인했는데 피그마보다 살짝 얇은 것 같아서요🥹🥹
찾아보니 CALayer 추가하는 방법도 있고 상단에 View를 추가하는 방법도 있더라구요 !!
저는 subLayer 추가하는 방식으로 구현해보았는데 호영님 편하신 방법대로 구현하셔도 될 것 같습니다..!!

2022-12-26 07:21 UTC, llghdud921 commented on FindTown/FindTownCore/Sources/FindTownCore/Base/BaseTabBarController.swift
> +
우와 이런 방식도 있었다니 처음 알았어요!!! 수정하도록 하겠습니다 :)

2022-12-28 08:55 UTC, llghdud921 reviewed
선영님!
borderline 선영님이 알려주신 CALayer 로직으로 개선했습니다!
훨씬 선명해진것같아요!! 🥰

2022-12-28 12:25 UTC, seonyoung42 approved these changes
고생하셨습니당 👍🏻👍🏻 !!!

2022-12-28 12:44 UTC, merged