화면전환을 위한 Coordinator 설정
YAPP-Github/21st-iOS-Team-1-iOS pull request #27
Opened 2022-12-25 09:19 UTC by llghdud921

## Motivation
- issue number : #18 

## Changes
- Coordinator 관련 protocol 구현
    - Coordinator 
    - FlowCoordinator, PresentationStyle enum
- AppCoordinator, TabCoordinator 구현 
- SceneDelegate내 AppCoordinator 실행하는 로직 구현
- BaseViewController내 hidesBottomBarWhenPushed 프로퍼티 설정하는 로직 구현

## Screen Shots
![Simulator Screen Recording - iPhone 11 - 2022-12-25 at 17 18 11](https://user-images.githubusercontent.com/40068674/209461330-d7bcd1f6-231d-47ef-8b10-27b14d1f4345.gif)

## To Reviewers
안녕하세요 선영님, 성훈님 :) 
화면전환을 위해 Coordinator 패턴을 구현했습니다 🥳
[기존의 Coordinator](https://lena-chamna.netlify.app/post/ios_design_pattern_coordinator_advanced) childCoordiantor, parentCoordinator를 가진 방식으로 구현을 하려다가 ChildFinish delegate를 하나하나 설정해주어야하고 메모리 관리에 크게 신경을 써야한다는 불편한 점이 있어서 구성에 도움을 얻는 글을 찾는 도중에 [CoordinatorsAutoHandled](https://github.com/AlbertMontserrat/CoordinatorsAutoHandled) 좋은 레퍼런스가 있어서 참고하였습니다 :)

### CoordinatorsAutoHandled
[블로그](https://medium.com/vptech/coordinator-pattern-in-swift-without-child-coordinators-42d482d15975)에도 아주 잘 나와있지만 간략하게 설명하지면 

<img width="661" alt="스크린샷 2022-12-25 오후 5 37 52" src="https://user-images.githubusercontent.com/40068674/209461804-fcbaff9e-f2e9-4dfb-a270-99273a04ab88.png">
MVVM으로 구성된 하나의 Coordinator인데요

- presenter는 navigationController로 강한 참조로 ViewController를 가지고 있습니다
- ViewController는 ViewModel을 가지고 있습니다
- ViewModel에는 강한 참조로 Cooridinator 가져 ViewModelDelegate에 해당하는 이벤트를 전달합니다 
- Coordinator에서 ViewModelDelegate가 위임한 이벤트를 실제로 실행하게 되고 
약한 참조로 presenter를 가져 viewController가 해제되는 경우 ViewController -> ViewModel -> Coordinator순으로 메모리가 자동으로 해제 되게 됩니다

### Coordinator protocol
Coordinator 프로토콜은 Coordinator의 공통 메서드인 start()를 추상화시켜 채택받게 하도록 구현하였습니다

### FlowCoordinator protocol
FlowCoordinator들을 구성하기 위한 프로토콜을 구현하였는데요!
구현에 필요한 presentationStyle, navigationController, start, initScene을 작성하였고 
start 메서드는 공통적으로 쓰이는 부분이기 때문에 extension을 이용하여 프로토콜 기본구현하였습니다

```swift
 public protocol FlowCoordinator: Coordinator {
    var presentationStyle: PresentationStyle { get set }
    var navigationController: UINavigationController? { get set }
    
    func start()
    func initScene() -> UIViewController
}

public extension FlowCoordinator {
    func start() {
        switch presentationStyle {
        case let .push(navigationController):
            self.navigationController = navigationController
            self.navigationController?.pushViewController(initScene(), animated: true)
        case .present(presenter: let presenter, modalPresentationStyle: let modalPresentationStyle):
            let navigationController = BaseNavigationController(rootViewController: initScene())
            self.navigationController = navigationController
            self.navigationController?.modalPresentationStyle = modalPresentationStyle
            presenter.present(navigationController, animated: true, completion: nil)
        case .setViewController(navigationController: let navigationController):
            self.navigationController = navigationController
            self.navigationController?.isNavigationBarHidden = true
            self.navigationController?.setViewControllers([initScene()], animated: true)
        case .none:
            self.navigationController = BaseNavigationController(rootViewController: initScene())
        }
    }
}
```

### PresentationStyle
PresentationStyle은 화면전환을 정리한 열거형으로 push, present, setViewController, none으로 구성되어 있는데요
- push는 새로운 Coordinator flow를 Push할때 사용합니다
- present는 새로운 Coordinator flow를 modally하게 띄워줄때 사용합니다 modalPresentationStyle로 overFullScreen, formSheet 등 설정할 수 있고 기본값은 automatic입니다
- setViewController는 TabCoordinator나 로그아웃하면 Login창을 띄우는 등 ViewHierachy를 초기화 시키려고 만들었습니다
- none은 TabBar로 구성된 Home, Map, Favorite, Setting Coordinator를 띄우려고 만들었어요 push 할순 없어서...

```swift
public enum PresentationStyle {
    case push(navigationController: UINavigationController)
    case present(presenter: UINavigationController, modalPresentationStyle: UIModalPresentationStyle = .automatic)
    case setViewController(navigationController: UINavigationController)
    case none
}
```

### AppCoordinator
AppCoordinator에서는 root Coordinator로 Coordinator flow를 처음 실행하는 로직을 담고 있어요! 
현재는 자동로그인 로직 구현을 위해 메서드 껍데기들을 만들어놓았습니다

### TabBarCoordinator
TabBarController를 담고있는 coordinator로 Home, Map, Favorite, Setting Coordinator를 생성합니다
지금은 Home이랑 Map만 만들어 두었습니다 :)

### Flow 예시
#### HomeCooridnator
- FlowCoordinator protocol로 기본구현을 해두어서 initScene메서드만 구현해주면 됩니다! 
- initScene에는 해당 Flow 초기화면인 ViewController를 반환해주어야합니다 ( ViewController가 ViewModel을 가지고 있어야함 )
- HomeCoordinator는 HomeViewModelDelegate를 채택하고 있어 메서드 내부에 새로운 Coordinator들을 push, present하는 로직을 구성할 수 있습니다!
- 추가로 ViewController만 push하고 싶다면  `secondScene()`메서드를 만들어서 push만 하면 됩니다! present도 마찬가지!!
`navigationController.pushViewController(secondScene(), animated: true)` 

```swift
final class HomeCoordinator: FlowCoordinator {

    var presentationStyle: PresentationStyle
    weak var navigationController: UINavigationController?
    
    init(presentationStyle: PresentationStyle) {
        self.presentationStyle = presentationStyle
    }
    
    internal func initScene() -> UIViewController {
        let homeViewModel = HomeViewModel(delegate: self)
        let homeViewController = HomeViewController(viewModel: homeViewModel)
        return homeViewController
    }
}

extension HomeCoordinator: HomeViewModelDelegate {
    
    func push() {
        guard let navigationController = navigationController else { return }
        MapCoordinator(presentationStyle: .push(navigationController: navigationController)).start()
    }
    
    func present() {
        guard let navigationController = navigationController else { return }
        HomeCoordinator(presentationStyle: .present(presenter: navigationController)).start()
    }
    
    func pop() {
        guard let navigationController = navigationController else { return }
        navigationController.popViewController(animated: true)
    }
    
    func dismiss() {
        guard let navigationController = navigationController else { return }
        navigationController.dismiss(animated: true)
    }
    
    func setViewController() {
        guard let navigationController = navigationController else { return }
        TabBarCoordinator(presentationStyle: .setViewController(navigationController: navigationController)).start()
    }
    
}
```

#### HomeViewController

HomeViewController는 ViewModel을 가지고 있습니다
```swift
class HomeViewController: BaseViewController {

    var viewModel: HomeViewModel?
```

#### HomeViewModel
HomeViewmodel은 delegate를 설정하여 실제 실행될 action을 명시하고 action을 coordinator에 위임하여 화면전환 로직을 건네주게 됩니다 
- 추가로 HomeViewModelType은 메서드 일일이 만들기 힘들어서 구현했어요.. 메서드 복붙만 하면 되니까요! 
```swift
protocol HomeViewModelDelegate {
    func push()
    func present()
    func pop()☺️
    func dismiss()
    func setViewController()
}

protocol HomeViewModelType {
    func push()
    func present()
    func pop()
    func dismiss()
    func setViewController()
}

final class HomeViewModel: BaseViewModel {
    let delegate: HomeViewModelDelegate
    
    init(delegate: HomeViewModelDelegate) {
        self.delegate = delegate
    }
}
```

### etc
- HomeFlow에 실제 Coordinator를 사용하는 테스트코드를 만들어두었어요 다음주중에 지우도록 하겠습니다!
- 메모리 누수는 다 체크해보았습니다! 메모리 누수 없어요!!!!!! 🥳
- 여러가지 화면전환 경우를 다 고려해보기는 했는데.. 제가 놓치는 부분이 있을 수도 있어서 추가 로직이나 개선 방안 말씀해주시면 바로 반영하겠습니다! 
- 변경된 코드가 많아 이해하기 힘드실수도 있는데ㅠ 언제든 DM주세요 🙂

2022-12-25 10:43 UTC, seonyoung42 commented
호영님 !! 정말 고생많으셨어요 ☺️
고민하신 흔적과 잘 설명해주시려는 마음이 너무 잘 느껴져요.. 🥹
다만 저는 처음 사용하는 패턴이라 코드를 이해하고 피드백 드리기에 시간이 조금 걸릴 것 같아요..!! 
정성들여 구현해주셔서 더 열심히 보고 싶은 마음도 있구요..!!
혹시나 기다리실까봐 미리 코멘트 달아놓아요..🥹🥹

2022-12-25 14:47 UTC, ungchun commented
와우.. 이렇게나.. 너무 고생많으셨습니다.. ㅠㅠ
저도 시간이 조금 걸릴 거 같지만.. 
열심히 작성해주신만큼 최대한 이해하려 노력하고 꼼꼼하게 읽어보고 피드백 드리겠습니다..!! 🥹👍

2022-12-27 07:32 UTC, seonyoung42 requested changes
호영님 구현해주신 Coordinator 패턴 잘 보았습니다 !! 
지금 당장은 바꿔주셨으면 하는 구조는 없고 탭바 버그만 수정해주시면 될 것 같습니다..!!
호영님 덕분에 편리하게 화면전환 할 수 있게 되었네요 👍🏻👍🏻 !!
정말 고생많으셨습니다 !!

2022-12-27 07:32 UTC, seonyoung42 commented on FindTown/FindTownCore/Sources/FindTownCore/Base/BaseViewController.swift
> +
호영님 TaBar 사라지는 버그 이 부분 때문에 발생하는 것 같아요..!!😰😰 혹시 hideBottomBarWhenPushed를 BaseVC에서 설정하시려는 이유가 있으실까요?!

2022-12-27 07:32 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/Common/Flow/TabBarCoordinator.swift
> +        return tabBarController
```suggestion
        let tabBarController: UITabBarController = BaseTabBarController()
        
        let homeCoordinator = HomeCoordinator(presentationStyle: .none)
        let mapCoordinator = MapCoordinator(presentationStyle: .none)
        
        homeCoordinator.start()
        mapCoordinator.start()
       
        guard let homeViewController = homeCoordinator.navigationController else { return UIViewController() }
        guard let mapViewController = mapCoordinator.navigationController else { return UIViewController() }
        
```
이 부분 기존 작성해주신 코드에 주석을 추가하시거나 혹은 위처럼 유사한 코드끼리 텝바 순서대로 작성하는건 어떨까용?☺️

2022-12-27 16:42 UTC, llghdud921 reviewed
코드가 별로긴 하지만ㅠㅠ 이게 그나마 잘 작동되어서 수정했구요ㅠㅠ 빨리 Scene 만들어야해서 우선 merge 요청드립니다 추후에 개선해보도록 할게요 :)

성훈님이 알려주신 방식 너무 감사해요! :)

2022-12-28 04:54 UTC, seonyoung42 requested changes
호영님...ㅠㅠㅠ 탭바 사라지는 버그가 그대로 있는데,, 저만 그런걸까요...🥺🥺🥺

2022-12-28 06:08 UTC, ungchun reviewed
탭바 버그는 사라졌네요!! 👍
정리도 자세하게 해두셔서.. 감사합니다!!
고생하셨습니다..!!!

2022-12-28 06:09 UTC, ungchun approved these changes

2022-12-28 06:23 UTC, seonyoung42 approved these changes
탭바 버그 수정되었네요 🥳🥳!!
그런데 setVC를 할 때만 네비바가 두꺼워지고 flip 트랜지션이 들어가 있던데 의도하신 걸까요?..
바쁘신 와중에 고생많으셨습니다 ☺️☺️ !!

2022-12-28 06:32 UTC, llghdud921 reviewed
선영님!
그게 제가 수정하지 못한 버그인데요ㅠㅠ 
TabBarController를 push하거나 Tab하는 경우 내부에 있는 HomeViewController의 navigationBar가 추가로 생겨나서 쌓입니다ㅠㅠ 
이것을 해결하려면 windows.rootViewController를 설정해야하는데 설계상 도저히 넣기힘들어서 우선 TabBar띄울때는 자체적으로 isNavigationBarHidden설정을 해야할 것같습니다

```swift
navigationController.isNavigationBarHidden = true
        TabBarCoordinator(presentationStyle: .push(navigationController: navigationController)).start()
```

현재 저희 앱 구조 상 TabBar를 SetViewController할 일은 없어보여서 우선 유지하려고 합니다 🥲
예제코드가 혼란이 올수있으니 homeCoordinator 내에 메서드들은 삭제해야겠네요ㅎㅎ 
꼼꼼한 코드리뷰 정말 감사드립니다!!

2022-12-28 07:03 UTC, merged