동네지도 인프라 UI 구현
YAPP-Github/21st-iOS-Team-1-iOS pull request #35
Opened 2023-01-05 08:33 UTC by seonyoung42

## Motivation
- issue number : #23 

## Changes
- 네이버 맵 띄우기
- 네비 바 구현
- icon collectionView 구현
- icon collectionView 선택시 나타나는 detailView 구현
- 탭 바 아이콘 수정
- 주소 팝업 띄우기

## Screen Shots
![Simulator Screen Shot - iPhone 13 - 2023-01-05 at 17 26 22](https://user-images.githubusercontent.com/77603632/210735717-11a7f46b-5d8f-43b5-9e98-dbf7a3eb730f.png)

## To Reviewers
+ 현재 피그마에 구현된 주소 팝업은 모두 버튼으로 구성되어 있어 추후에 동이 추가되면 팝업이 비대해질 수있고, 팝업 내에서 화면 전환이 일어나야하는 구조라 디자이너분께 회원가입 플로우의 관심동네 설정 화면과 유사하게 드롭다운으로 변경하는게 어떠한지 제안드렸고 검토 후 다시 말씀주신다고 하셔서 아직 구현하지 않았습니다
+ 서버에서 어떻게 데이터가 들어올지 몰라 임시 데이터 구조(MapData.swift)설계해서 구현하였고 추후 수정 예정입니다 
+ 한 가지 해결 못한 버그가 있는데요... 다른 탭을 들어갔다 다시 동네지도 탭으로 돌아오면 icon들의 이미지 tintcolor가 default색상인 systemblue로 변경됩니다.. 혹시 이렇게 되는 이유가 뭘까요?😰..
+ 저도 RxSwift만 사용해보는건 처음이라.. 피드백 환영입니당 🥹!!

2023-01-05 15:56 UTC, ungchun commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +    let detailCategoryView = MapDetailCategoryView()
```suggestion
final class MapViewController: BaseViewController {
    
    private let mapView = NMFMapView()
    private let naviBarSubView = UIView()
    private let rightBarButton = UIBarButtonItem(image: UIImage(named: "favoriteBtn"),
                                         style: .plain,
                                         target: nil,
                                         action: nil)
    private let addressButton = UIButton()
    private let mapToggle = MapSegmentControl(items: ["인프라", "테마"])
    private let detailCategoryView = MapDetailCategoryView()
```  

final, private 붙일 수 있는 곳에는 붙이는게 좋아보입니다!!

2023-01-05 16:02 UTC, ungchun commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +     }
제가 잘 이해는 못했지만.. 셀을 클릭하면 기존의 뷰를 remove 시키고 for문으로 data를 add 시키는 거 같은데 이렇게 작성하신 이유가 있을까요..?! 🤔 나중에 서버와 어떻게 연동해서 데이터를 가져올지 모르겠지만 셀을 클릭할 때마다 for문이 계속 돌아야하나..? 생각이 들어서요 ㅎㅎㅎ

2023-01-05 16:13 UTC, ungchun requested changes
선영님..! 고생하셨습니다!! 😀😀

- 지도에 들어가면 이런 로그가 떠요..! 컬렉션 뷰 레이아웃 설정관련해서 나는 거 같아요..! 확인부탁드립니다!!
```
2023-01-06 01:02:47.810680+0900 FindTown[15080:5727926] The behavior of the UICollectionViewFlowLayout is not defined because:
2023-01-06 01:02:47.810791+0900 FindTown[15080:5727926] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2023-01-06 01:02:47.810845+0900 FindTown[15080:5727926] Please check the values returned by the delegate.
2023-01-06 01:02:47.811239+0900 FindTown[15080:5727926] The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x123768750>, and it is attached to <UICollectionView: 0x1249eb400; frame = (0 16; 390 32); clipsToBounds = YES; autoresize = W; gestureRecognizers = <NSArray: 0x6000024eae50>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x600002a26020>; contentOffset: 
```

- popup View를 present 할때, dismiss 할때 애니메이션이 어색하다고 생각이 들어요..! 검은색 배경이 따라 올라오니.. 아직 주소팝업에 대해 추후에 작성하신다고 하니 혹시나 나중에 사용하신다고 하시면 애니메이션은 빼는게 더 나아 보이네요..!

- 필터 버튼은 제가 Icon Filter로 버튼을 만들어놨는데 커스텀으로 만드셨더라구요..! 근데 요 버튼은 제가 수정을 해야할 거 같아서 나중에 수정하고 올리면 그때 사용하시면 될 거 같습니다! 😀

![스크린샷 2023-01-06 오전 1 06 57](https://user-images.githubusercontent.com/50910456/210826290-74b91051-f054-4e5f-993c-fb58f0f18c80.png)

- [throttle](https://ios-development.tistory.com/176) 저도 요번에 rx 작성하면서 알게된 개념인데 버튼 중복 입력 방지때문에 넣으면 좋은 거 같더라구요..! 👍

2023-01-05 16:59 UTC, llghdud921 requested changes
선영님!
고생많으셨습니다 👍

다른것은 다 코멘트에 남겼구요! 
detailCategoryView에 대해서 말씀드리자면 init메서드에 데이터를 받아 View를 그리게끔 만들면 좋지 않을까 생각을 해봅니다ㅎㅎ 개선하면 좋을 것 같아요!

2023-01-05 16:59 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/AddressPopUp/AddressPopUpViewController.swift
> +    let stackView3 = UIStackView()
CollectionView로 그리는것이 훨씬 코드가 깔끔할 것 같습니다..!!

2023-01-05 16:59 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/MapCollectionViewCell.swift
> +        setupLayout()
해당 코드들은 init메서드에 위치하는 것이 좋을 것 같습니다 :)

2023-01-05 16:59 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/MapCollectionViewCell.swift
> +        self.heightAnchor.constraint(equalToConstant: 32.0).isActive = true
요건 Layout 메서드 내에 위치하구요!

2023-01-05 16:59 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +    let rightBarButton = UIBarButtonItem(image: UIImage(named: "favoriteBtn"),
favoriterButton이라는 네이밍이 더 좋을 것 같습니다!

2023-01-05 16:59 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
> +        let categories = [Category(image: UIImage(named: "martIcon")?.withRenderingMode(.alwaysTemplate) ?? UIImage(),
선영님이 홈화면 다녀오면 tintColor가 reset된다고 하셨는데 withRenderingMode때문일 것 같습니다 
아마 홈화면 다녀왔을때 color를 set해주는 로직이 없어서 dataSource내에 있는 이미지가 적용되는 것 같아요

개선하면 좋을 것 같습니다 😃

2023-01-06 01:36 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +     }
셀 별로 추가되는 detail 데이터의 갯수(예를 들면 마트&편의점 -> 3개, 카페 -> 1개)를 미리 알 수가 없어서 이렇게 작성했습니다 😂😂 더 좋은 방법이 있을까요?!

2023-01-06 01:37 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +    let detailCategoryView = MapDetailCategoryView()
아하 넵 감사합니다 !

2023-01-06 01:46 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/Map/AddressPopUp/AddressPopUpViewController.swift
> +    let stackView3 = UIStackView()
이 파일 삭제된 줄 알았는데 올라갔네요 😂😂..이 부분은 신경 안쓰셔도 될 것 같습니다 !

2023-01-06 01:47 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/Map/MapCollectionViewCell.swift
> +        setupLayout()
ㅎㅎ 수정했습니다!

2023-01-06 08:54 UTC, seonyoung42 commented
+  iconCell 내의 image 색상 변경되는 버그
     + image.tintcolor 로 처리하니 color를 설정해주어도 다시 default 색상으로 돌아가기에 아예 이미지 위에 색상을 입히는 방법으로 변경하였습니다.
+ detailCategoryView 데이터 설정 메서드
     + 우선 이 부분은 추후 다시 수정될 예정입니다.. ! cell 클릭시마다 데이터가 달라지기 때문에 init보다는 public 메서드를 사용하고자 했는데 데이터 형식이 아직 정해지지 않은 상태라 우선 패키지가 아닌 앱에서 구현해놓았습니다. 리뷰 주신 for 문으로 처리한 이유는 데이터의 갯수가 매번 달라지기 때문인데,, 어떤 다른 방법이 있는지 잘 모르겠습니다 😂 
+ collectionView Layout 관련 로그
   + collectionView cell들의 width를 self sizing 해놓은 메서드에 의해 출력되는 로그여서 이대로 두어야할 것 같아요 😅
+ 그 외에 리뷰 주신 네이밍, 코드 위치 등 수정했습니다 감사합니다 ☺️

2023-01-06 13:11 UTC, llghdud921 approved these changes
선영님! 고생많으셨습니다 👍

2023-01-06 13:20 UTC, ungchun approved these changes
고생하셨습니다..!!! 😀

필터 버튼을 수정해서 적용을 해보면 좋을 거 같네요! 제가 처음에 버튼 만들 때 조금 더 신경써서 만들었다면.. ㅠㅠㅠㅠㅠㅠ

2023-01-06 13:48 UTC, merged