회원가입 관심 있는 동네, 약관동의 Scene
YAPP-Github/21st-iOS-Team-1-iOS pull request #39
Opened 2023-01-09 16:12 UTC by ungchun

## Motivation
- issue number : #19 

## Changes
- coordinator delegate 이름 변경
- success, error color set 추가
- 기존 scene에 추가된 label들 추가
- keyboardFocusing 필요한 scene들 기존 뷰에서 stackView로 변경
- 관심 있는 동네, 약관동의 scene 추가
- dropDown Proxy 추가

## Screen Shots

![Simulator Screen Recording - iPhone 14 - 2023-01-10 at 00 54 48](https://user-images.githubusercontent.com/50910456/211350871-98a06030-2878-446f-8794-899b1fa6dd65.gif)

## To Reviewers
- 남은 관심 있는 동네, 약관동의 scene을 추가했습니다..!!
- BaseNavigationController에 있던 backButtonImage image 파일이 FindTownUI module에 있는 거라 못가져오더라구요.. 이것저것 막 경로 넣고 해봤는데.. 음.. 힘들 거 같아서 Core에도 Resource를 추가했습니다..! 😢
-  키보드 올라오면 스크롤 필요한 씬들 호영님께서 만드신 stackView에 추가해서 뷰를 수정했습니다..! stackView 가지고 autolayout 다시 그리려니 너무 어렵더라구요.. ㅠㅠㅠㅠ
- 어제 피드백 받았던 coordinator delegate 이름 바꿨는데 확인부탁드려요..! 😀
- 호영님께서 추천해주신 delegateProxy 방법으로 dropDown 수정해봤습니다..!! 괜찮나요..? 처음 해보는거라 시간이 꽤 걸렸지만 너무 좋은 방법인 거 같아요.. 좋은 공부가 된 거 같습니다..!! 감사합니다 호영님 !! 👍
- dropDownProxy를 위치를 FindTownUI의 DropDown에 같이 빼고 싶어서 기존에 없었던 FindTownUI dependencies에 RxSwift를 추가했습니다. 그리고 DelegateProxy를 쓰려면 RxCocoa를 사용해야하는데 [No such module 'RxCocoaRuntime'](https://github.com/ReactiveX/RxSwift/issues/2277) 이 에러가 계속 나더라구요.. 계속 찾다 찾다가 ["Missing Package Product" errors when using RxSwift 5.1.1 with SPM on Xcode 11.5](https://github.com/ReactiveX/RxSwift/issues/2194) 여기서 답을 찾아서 dependencies 수정해서 추가했습니다..!  
<br>

- 회원가입 시 필요한 데이터들은 next로 넘기면서 세팅이 가능해서 모델만 만들면 됩니다. 카카오, 애플 로그인과 같이 작업을 할 예정입니다..!!
- 양이 좀 많은 거 같네요.. ㅠㅠㅠㅠㅠ 😅 오타나, 어색하거나 이상한부분 있으면 피드백 마구 달아주세요!!

2023-01-10 13:00 UTC, llghdud921 requested changes
성훈님! 고생많으셨습니다 👍👍

- 살고있는 지역 input받을때 errorlabel이 계속 보이는점
errorLabel이 계속 보여서 UX상으로 좋지 않을 것 같다고 생각이 듭니다 그래서 buttonSelect인 output으로 Label hidden처리를 하면 좋을 것 같은데요!
trigger를 input dong이 아닌 combineLatest내에 바인딩을 하면 좋을 것 같다는 생각이드네요..!!
(이렇게 하려면 다른 코드도 수정해야해요!, 네이밍도..)
잘 이해되지 않으신다면 DM주세요

```
Observable.combineLatest(input.dong, input.year, input.month)
            .subscribe(onNext: { (dong, year, month) in
                if dong == "" {
                    self.output.buttonsSelected.accept(true)
                } else {
                    self.output.buttonsSelected.accept(false)
                    let model = DongYearMonthModel(dong: dong, year: year, month: month)
                    self.input.dongYearMonth.onNext(model)
                }
            })
            .disposed(by: disposeBag)
```

- Button enable 관련
Button Enable 속성때문에 trigger 바인딩 코드가 복잡해지는 것 같네요... 
이부분은 저도 고민해보면서 개선해나아가면 좋을 것 같아요!

2023-01-10 13:00 UTC, llghdud921 commented on FindTown/FindTown/Presentation/AuthScene/Flows/LoginViewModelDelegate.swift
> +protocol LoginViewModelDelegate {
👍👍👍

2023-01-10 13:00 UTC, llghdud921 commented on FindTown/FindTownCore/Sources/FindTownCore/Base/BaseNavigationController.swift
> +        let backButtonImage = UIImage(named: "Back", in: .module, compatibleWith: nil)?.withAlignmentRectInsets(UIEdgeInsets(top: 0.0, left: -8.0, bottom: -8.0, right: 0.0))
흐음.... package에서 resource 가져오는게 잘 안되나보네요.....ㅠㅠ
이 부분 제가 한번 살펴보겠습니다

2023-01-10 13:00 UTC, llghdud921 commented on FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
>          }
아이코... 제가 말씀을 못드렸군요..
nextButton같은 bottomButton은 stackView가 아닌 view에 추가해서 layout을 잡아주셔도 될것같아요!

2023-01-11 05:57 UTC, seonyoung42 reviewed
성훈님 고생많으셨습니다 !!
delegateProxy 개념은 저도 이번에 처음 보는거라 신기하네요 ! 공부해봐야할 것 같습니다 👍🏻!
다른 부분은 확인했는데 UI 구현에서 두 가지 빠트리신 것 같아요!
+ LocationAndYearsViewController의 whereIsNowTitle.topAnchor.constraint 값 잘못 설정되어 있음
+ TownMoodViewController에서 townLikeTextView에 작성할 때 TextView layer 색상이 바뀌지 않음

2023-01-11 08:30 UTC, ungchun commented
- 기존 FTButton에서 isSeleted didSet이 불릴때마다 configuration에 재 할당해서 동일한 값을 주면 title이 사라지는 문제가 있었습니다.. 그래서 didSet하면 configuration의 요소들을 하나씩 수정해주는 방법으로 수정했습니다!!
```
public override var isSelected: Bool {
        didSet {
            // configuration = configureUI(style)
            configureUI(style: self.buttonStyle)
        }
    }
```
- 계속 isSeleted, isEnabled 값이 같이 수정되는 경우에 두번 코드를 작성해야 했었는데 FTButton에 func을 하나 만들었습니다!
```
 /// isEnabled, isSelected 값이 똑같이 바껴야 하는 경우 사용
    public func isEnabledAndSelected(_ isEnabledSelected: Bool) {
        self.isSelected = isEnabledSelected
        self.isEnabled = isEnabledSelected
    }

// 사용
 private func buttonStatusChange(_ isStatus: Bool) {
        duplicateButton.isEnabledAndSelected(isStatus)
        nextButton.isEnabledAndSelected(!isStatus)
    }
```

- 살고있는 지역 errorLabel 호영님께서 주신 코드로 변경했는데, dong에 값이 들어가야 hidden 처리가 돼서.. 결과는 똑같지만 코드는 더 간결해졌습니다..!! 👍

- nickName, TownMood View stackView로 작업하던 거 keyboard scroll 문제때문에 다시 되돌렸습니다..!!

- 기존에 사용중이던 hideKeyboard 이 친구가 빈 공간이 아니라 어떤 탭을 하더라도 keyboard가 내려가더라구요.. (중복확인 버튼이나 택스트필드의 x버튼을 탭해도 내려감) 그래서 BaseViewController에 touchesBegan로 처리했습니다..!

```
extension UIViewController {

    /// 화면 탭시 키보드 숨기기
    public func hideKeyboard() {
        let tapGesture = UITapGestureRecognizer(target: self,
                                                action: #selector(UIViewController.dismissKeyboard))
        tapGesture.cancelsTouchesInView = false
        view.addGestureRecognizer(tapGesture)
    }
}

private extension UIViewController {
    @objc func dismissKeyboard() {
        view.endEditing(true)
    }
}

// In BaseViewController
open override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?){
        self.view.endEditing(true)
    }
```
- 그래서 현재 BaseViewController에 hideKeyboard (키보드), setUpNotification (NotificationCenter 겹침) 두개가 주석처리되어 있는데 확인해보시고 필요없으시다면 지우도록 하겠습니다..!!

2023-01-11 10:05 UTC, llghdud921 approved these changes

2023-01-11 10:27 UTC, seonyoung42 approved these changes
성훈님 고생많으셨습니다 !!

2023-01-11 10:27 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
> +        guard let keyHeight else { return }
여기 잘못된 것 같아용..!!

2023-01-11 12:21 UTC, merged