동네지도 테마 구현 및 AddressSheetVC 구현
YAPP-Github/21st-iOS-Team-1-iOS pull request #40
Opened 2023-01-10 11:38 UTC by llghdud921

## Motivation
- issue number : #24 

## Changes
- MapScene 리팩토링을 진행하였습니다
- AddressSheetViewController, AddressSheetViewModel 구현하였습니다 
- City, Country, Map data 등 데이터타입은 domain layer Entitiy로 이동하였습니다

## Screen Shots
![Simulator Screen Recording - iPhone 14 Pro Max - 2023-01-10 at 20 31 36](https://user-images.githubusercontent.com/40068674/211541339-db47dc73-a754-45e3-803c-3073ec66e3c7.gif)

## To Reviewers
- 행정동 명칭을 찾아보니까 구는 County, 동은 Village라고 되어있어서 우선 네이밍을 이렇게 지었어요! 백엔드 erd 받아보고 수정할수도 있습니다!
- County에 constant처럼 데이터 넣어놓았으니 다른코드에서 사용하셔도 좋을 것 같아요! 근데 이파일을 constant라고 네이밍 해야할지 고민이 되네요.. enum으로 해서ㅠㅠ
- villageCollectionView에 item이 하나인경우 가운데 정렬이 되어있는데.... 이부분 구현이 복잡해서 추후에 구현하도록 하겠습니당
- Coodinator간 데이터 전달에서 고민이 되는 부분이 있어서 추후에 parentCoordinator를 추가할 것 같아요.. coordinator 너무 어렵네요ㅠ 우선 화면 그리는것을 중점으로 진행합시다!

2023-01-10 17:38 UTC, ungchun commented on FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapDetailCategoryView.swift
>  public class MapDetailCategoryView: UIView {
```suggestion
final class MapDetailCategoryView: UIView {
```

이거 아마 빼오시면서 public 삭제하는거 까먹으신 거 같아요..!! 
MapDetailCategoryView, MapDetailComponentView 2개입니다~~

2023-01-10 17:49 UTC, ungchun commented on FindTown/FindTown/Presentation/MapScene/AddressSheet/AddressSheetViewController.swift
> +    }
```suggestion
    var completeButtonEnabled: Binder<Bool> {
        return Binder(self.base) { (viewController, isEnabled) in
            if isEnabled == true {
                viewController.completeButton.isSelected = true
                viewController.completeButton.isEnabled = true
            } else {
                viewController.completeButton.isSelected = false
                viewController.completeButton.isEnabled = false
            }
        }
    }
```

우선 isEnabled 값도 줘야합니다..!
음.. 호영님께서 제 리뷰에 달아주신걸 봤습니다..!
보통은 isSeleted랑 isEnabled랑 같은 값을 가져서 func으로 빼도 괜찮을 거 같긴한데
다른 값을 가지는 경우도 생길 거 같아서 고민이네요..
예를 들어 버튼 스타일은 isSeleted false 스타일을 가지는데 반대로 선택은 할 수 있는 경우..
func으로 따로 만들고 예외로 이런 상황만 따로 값을 주는 쪽으로 가면 별로일까요..?!

2023-01-10 18:05 UTC, ungchun requested changes
호영님! 너무 고생하셨습니다..👍 View 양이 엄청 나네요.. ㄷㄷ;; 

- 저는 네이밍에 능숙하지는 못하지만 County 네이밍 괜찮은 거 같습니다..! 😀
- 엄청난 성능향상? 은 기대하기는 어렵다지만 저는 상속안하는 class에 final, private 붙일 수 있는 부분에는 전부 private를 붙이면 좋다고 알고 있어서요..!! 추가할 수 있다면 추가하는게 좋을 거 같아요! 😀😀

![스크린샷 2023-01-11 오전 2 50 54](https://user-images.githubusercontent.com/50910456/211625612-3d40a704-ea24-41a6-a81d-d90f0cb43d21.png)
- 이 친구는 여전히 말썽이군요 ㅋㅋㅋㅋ;;

![Simulator Screen Recording - iPhone 14 - 2023-01-11 at 02 31 45](https://user-images.githubusercontent.com/50910456/211625848-36203b72-7f30-4342-98d7-72f9a79c8f24.gif)

- button의 isSeleted에 동일한 값을 주면 이렇게 title이 사라지는 문제가 있었습니다.. ( isSeleted 값이 true인데 true를 주거나 isSeleted 값이 false인데 false를 주는 상황 ) 이 문제 해결을 했습니다.. 제 PR에 같이 올리면서 코멘트 달아놓을게요..! 호영님은 신경안쓰셔도 괜찮으셔서 적어놓습니다!!
- isEnalbed 초기값 주는 것도 위에 거랑 같이 올리겠습니다..

- 호영님 리뷰인데, 왜 까면 깔수록 제부분에서 문제가 터지는지.. 얼른 수정해서 올리겠습니다..! 😅

2023-01-11 03:15 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapDetailCategoryView.swift
>  public class MapDetailCategoryView: UIView {
오 맞네요!! 수정하겠습니다~!

2023-01-11 03:29 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/AddressSheet/AddressSheetViewController.swift
> +    }
func으로 따로 빼는것 좋을 것 같아요! 👍

2023-01-11 03:30 UTC, llghdud921 reviewed
성훈님 꼼꼼하게 봐주셔서 너무 감사드립니다ㅎㅎ
뷰를 많이 만들어서 그런지 세세하게 살피지 못했네염..

코멘트 달아주신 부분 전부 수정적용 하였습니다! 감사합니다 :)

2023-01-11 05:42 UTC, ungchun approved these changes
고생많으셨어요!!! :) 😀

2023-01-11 07:04 UTC, seonyoung42 reviewed
호영님 고생 많으셨습니다 !!
파일 양이 많아 제대로 다 확인을 했는지 잘 모르겠네요 😅
추가로 MapStoreCollectionViewCell의 layout이 잘못설정되어있는것 같습니다ㅠㅠ 가게의 주소가 한 줄일때와 두 줄일때 레이아웃이 달라지더라구요..!

2023-01-11 07:04 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/AddressSheet/AddressSheetViewController.swift
> +            villageCollectionView.topAnchor.constraint(equalTo: titleLabel.bottomAnchor, constant: 32.0),
여기 countyCollectionView와 villageCollectionView의 topAnchor constant 값이 달라요..!

2023-01-11 07:04 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/AddressSheet/AddressSheetViewController.swift
> +                viewController.backButton.isHidden = false
여기에 viewController.titleLabel.text = "" 도 들어가야하지 않을까 싶어요 !
지금은 titleLabel 텍스트가 바뀌지 않고 있어서요 😅!

2023-01-11 07:04 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/AddressSheet/AddressSheetViewController.swift
> +            .disposed(by: disposeBag)
```suggestion
        countyCollectionView.rx.modelSelected(County.self)
            .map { county in
                return county.villages.map { City(county: county, village: $0) }
            }
            .delay(.milliseconds(400), scheduler: MainScheduler.instance)
            .subscribe(onNext: { cities in
                self.viewModel?.output.villageDataSource.onNext(cities)
                self.rx.cityType.onNext(.village)
            })
            .disposed(by: disposeBag)
```
사용자가 선택한 구를 보여주고 동 선택으로 넘어가는게 조금 더 자연스럽지 않을까 싶어서 delay를 넣는건 어떨지 제안드려봅니당..!

2023-01-11 07:27 UTC, seonyoung42 reviewed
여기만 수정하니 레이아웃이 알맞아지는것 같습니다..! ☺️

2023-01-11 07:27 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapStoreCollectionViewCell.swift
> +        stackView.spacing = 0
```suggestion
        stackView.distribution = .fill
        stackView.spacing = 2
```

2023-01-11 07:27 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapStoreCollectionViewCell.swift
> +        }
```suggestion
        [nameLabel, addressLabel, emptyView2].forEach {
            $0.translatesAutoresizingMaskIntoConstraints = false
            titleStackView.addArrangedSubview($0)
        }
        
        titleStackView.heightAnchor.constraint(equalToConstant: 70.0)
```

2023-01-11 08:28 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/AddressSheet/AddressSheetViewController.swift
> +            villageCollectionView.topAnchor.constraint(equalTo: titleLabel.bottomAnchor, constant: 32.0),
어머어머 조정하는 과정에서 다시 수정을 안했네요!! 🥲

2023-01-11 08:28 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/AddressSheet/AddressSheetViewController.swift
> +            .disposed(by: disposeBag)
좋은 것 같습니다! 바로 반영하겠습니다 👍

2023-01-11 08:31 UTC, llghdud921 commented
> 호영님 고생 많으셨습니다 !! 파일 양이 많아 제대로 다 확인을 했는지 잘 모르겠네요 😅 추가로 MapStoreCollectionViewCell의 layout이 잘못설정되어있는것 같습니다ㅠㅠ 가게의 주소가 한 줄일때와 두 줄일때 레이아웃이 달라지더라구요..!

선영님! 이것이 토요일에 의논되었던 내용인데요! 두줄이상될 경우 spacing이 줄어들게 하려고 일부러 이렇게 구현한것입니다!!
팀회의때 논의된 내용이라 description에 제대로 설명을 못했었네요..ㅠㅠ 
추후에 디자인 확정되면 수정될 것 같아요!

2023-01-11 08:42 UTC, merged

2023-01-11 09:01 UTC, seonyoung42 commented
엇 그래요?! 피그마에는 그렇게 반영이 안되어 있어서 수정된 줄을 몰랐네요 😅
그런데 어느 부분 spacing이 줄어드는지는 지금 명확히 모르겠지만ㅠㅠ Cell안의 title 위치는 항상 고정이어야하지 않을까요?.. 🥲🥲 디자인의 요소로 봐야하는 부분인지 잘 모르겠네요..ㅠㅠ

2023-01-11 09:08 UTC, llghdud921 commented
> 엇 그래요?! 피그마에는 그렇게 반영이 안되어 있어서 수정된 줄을 몰랐네요 😅
> 
> 그런데 어느 부분 spacing이 줄어드는지는 지금 명확히 모르겠지만ㅠㅠ Cell안의 title 위치는 항상 고정이어야하지 않을까요?.. 🥲🥲

네네 타이틀은 고정으로 가야할 것 같아요!
폰트를 줄일지 spacing을 줄여야하는지 조정하는 과정이어서 수정안했어요! 
제가 복사버튼도 안했고 해서 추후에 수정 예정입니다ㅎㅎ