카카오 로그인
YAPP-Github/21st-iOS-Team-1-iOS pull request #45
Opened 2023-01-12 12:08 UTC by ungchun

## Motivation
- issue number : #42 

## Changes
- 카카오 버튼 색상 변경
- 카카오 SDK SPM 추가
- 카카오 로그인 기본 기능 구현 (서버 연동 x)
- KeyChain Manager 추가

## Screen Shots
![ezgif com-gif-maker](https://user-images.githubusercontent.com/50910456/212057970-87f8ccc4-b30b-48b3-9de3-d39dc8da6a89.gif)

## To Reviewers
- 흠.. close를 하지 말걸 그랬네요.. 😅
- 기존 UserDefault를 사용해서 세팅했던걸 KeyChain으로 변경했습니다..!! 그래서 userDefaultUtil에 nickname만 남겨놨는데 필요없다고 판단되면 삭제하겠습니다..!!
- oauth 2.0 개념이 모르는 중에 계속 쓰고 있었던 친구였다니.. 이렇게 또 배웁니다.. 그리고 KeyChain 관련 100% 이해했다고 하면 거짓말이고 어느정도 사용법을 이해한 상태입니다. 찾아보니 다들 쓰는 코드 형태가 비슷비슷하네용.. 현재 accessToken, refreshToken 값만 저장하고 있습니다. 추후에 더 필요하면 넣겠습니다아..!
- 자동로그인 로직은 어쨌든 키체인의 토큰값을 가지고 이리저리 처리할 거 같은데 조금 더 고민해봐야 할 거 같습니다..
- ViewModel에 있는 DongYearMonth, JachiguDong, SignupUserModel 들은 나중에 한번에 뺄 예정입니다!
- 지금 당장 네트워크 관련해서 세팅도 안됐고 완성도 아니라서 전체적인 흐름?, KeyChain, signinManager 관련해서 많은 피드백 부탁드립니다!!

2023-01-14 15:52 UTC, seonyoung42 reviewed
성훈님 수고 많으셨습니다..!!
저도 새로 공부해보는 개념들이 많아 리뷰가 늦어졌네요 죄송해요..🥹🥹

2023-01-14 15:52 UTC, seonyoung42 commented on FindTown/FindTown/Manager/KakaoSigninManager.swift
> +}
이렇게 커스텀 error 사용하는거 넘 좋은것같아요 👍🏻 !!

2023-01-14 15:52 UTC, seonyoung42 commented on FindTown/FindTown/Domain/Manager/KeyChain/KeyChainManager.swift
> +    func create(account: KeyChainAccount, data: String) throws {
성훈님..! 여기 찾아보니까 반환타입이 create와 delete는 Bool, read는 string? 이면 나중에 사용하시기 더 편리하지 않을까 싶어서요..! 제가 참고했던 레퍼런스 보낼게요!!

2023-01-14 15:52 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/Utils/UserDefaultUtil.swift
> +struct UserDefaultUtil {
저희 UserDefault들을 PropertyWrapper로 관리하는거 어떨까요?! 다만 성훈님은 지금 userdefaults를 사용하고 계시지 않으니까 나중에 제가 추가해도 괜찮을 것 같아요..!!

2023-01-17 07:21 UTC, llghdud921 requested changes
성훈님! 고생많으셨습니다!!리뷰 너무 늦어서 죄송해요,,,,,ㅠㅠ

- 지훈님께 여쭤봐야하긴하지만 Token내 expiredTime이 추가될 예정이라서 이부분 토큰을 model로 관리해도 될것같습니다! (논의해보시고 말씀해주세요)

2023-01-17 07:21 UTC, llghdud921 commented on FindTown/FindTown/Application/SceneDelegate.swift
> +        AppCoordinator(navigationController: navigationController, userDefaults: userDefaultUtil).start()
이거 coordinator에 넣는 이유가 무엇일까요 🙃

2023-01-17 07:21 UTC, llghdud921 commented on FindTown/FindTown/Domain/Manager/KeyChain/KeyChainError.swift
> +
띄어쓰기 고쳐주세요...

2023-01-17 07:21 UTC, llghdud921 commented on FindTown/FindTown/Manager/KakaoSigninManager.swift
> +enum BaseError: LocalizedError {
baseError보다는 kakaoLoginError, NetworkError로 세분화하면 더 좋을 것 같습니다!!

2023-01-17 07:21 UTC, llghdud921 commented on FindTown/FindTown/Manager/SigninManagerProtocol.swift
> +    func logout() -> Observable<Void>
protocol coding convention이 이렇게 띄어쓰는것보다 붙이는것이 더 좋을 것같아요

2023-01-17 07:21 UTC, llghdud921 commented on FindTown/FindTown/Manager/SigninManagerProtocol.swift
> +    var value: String {
description이 더 좋을 것 같아요!

2023-01-17 07:21 UTC, llghdud921 commented on FindTown/FindTown/Manager/SigninManagerProtocol.swift
> +        }
이렇게 사용되면 rawValue에 넣어도 될것같구요...

2023-01-17 13:18 UTC, ungchun commented on FindTown/FindTown/Presentation/Utils/UserDefaultUtil.swift
> +struct UserDefaultUtil {
사실 제가 PropertyWrapper 에 익숙하지 않아서 딱 보면 이거 써야지! 생각이 잘 안드네요 ㅠㅠㅠㅠ 현재는 userdefaults 사용하지는 않으니 선영님이 사용하시면 추가하시면 너무 좋을 거 같아요!! ㅎㅎㅎㅎㅎ

2023-01-17 13:19 UTC, ungchun commented on FindTown/FindTown/Application/SceneDelegate.swift
> +        AppCoordinator(navigationController: navigationController, userDefaults: userDefaultUtil).start()
userDefaults 사용하지 않아서 삭제시켰습니다..! 사실 사용한다해도 coordinator에 넣는건 좋지 않아 보이네요..!

2023-01-17 13:21 UTC, ungchun commented on FindTown/FindTown/Manager/KakaoSigninManager.swift
> +enum BaseError: LocalizedError {
NetworkError + kakao, apple 로그인 같이 사용할 수 있게 SocialLoginError 로 세분화 시켰습니다..! 너무 좋아요 ㅎㅎㅎㅎ 😀

2023-01-17 13:21 UTC, ungchun commented on FindTown/FindTown/Manager/SigninManagerProtocol.swift
> +    func logout() -> Observable<Void>
수정했습니다!! 😄

2023-01-17 13:23 UTC, ungchun commented on FindTown/FindTown/Manager/SigninManagerProtocol.swift
> +        }
rawValue로 사용하게 수정했습니다..!! enum.. 사용법이 참 다양하고 어렵네용 ㅠㅠㅠㅠ

2023-01-18 04:43 UTC, ungchun commented
- 리뷰해주신 내용들을 바탕으로 코드들 수정했습니다..!!
- network 세팅이 끝나는대로 바로 추가 작업하겠습니다..!!
- 늘 꼼꼼한 리뷰에 감사드립니다..!! 😀 추가 피드백은 환영이랍니다 ㅎㅎㅎㅎ

2023-01-18 09:36 UTC, seonyoung42 approved these changes
성훈님 고생많으셨습니다  👍🏻 !!

2023-01-18 09:38 UTC, llghdud921 commented on FindTown/FindTown/Application/SceneDelegate.swift
> +        AppCoordinator(navigationController: navigationController, userDefaults: userDefaultUtil).start()
앗! userDefaults에 들어가는것을 궁금했던 것이 었어요...!!
coordinator에 넣는것은 큰 문제는 없습니다용 근데 SceneDelegate에서 주입하는것은 고민이 되긴하네요..
이부분 DIContainer를 사용하는것도 고려를 해봐야겠습니다!

2023-01-18 09:39 UTC, llghdud921 approved these changes
성훈님
이번 PR은 확정된게 많이 없어서 우선 코멘트를 많이 안드렸어요!
네트워크 설계작업하시고 수정이 많이 될것같습니다!

2023-01-18 10:43 UTC, merged