홈 메인 + 필터 화면 구현
YAPP-Github/21st-iOS-Team-1-iOS pull request #49
Opened 2023-01-19 15:14 UTC by ungchun

## Motivation
- issue number : #37 

## Changes
- 동네 리스트 테이블 화면 
- 필터 바텀시트 화면

## Screen Shots
![Simulator Screen Recording - iPhone 14 - 2023-01-19 at 18 52 47](https://user-images.githubusercontent.com/50910456/213411173-f811c13e-d19d-4b82-b9c9-5573d07ea814.gif)

## To Reviewers
- 생각보다 좀 코드가 많네요 ㅠㅠㅠㅠㅠㅠ 죄송합니다....
- 필터 시트에 탭맨 기능을 빼신다고하셔서 구현을 하다가 삭제했습니다..!! 😀
- 바텀시트를 사용하실 때 dismiss를 따로 줘버리면 애니메이션이 이상하더라구요. 살펴보니 BaseBottomSheetViewController에 setBottomSheetStatus를 사용하면 될 거 같아 테스트해봤더니 자연스럽게 dismiss 처리됩니다..! 바텀시트 사용하시는 분들은 이렇게 사용하시면 될 거 같아요~~ 😆
<img width="443" alt="스크린샷 2023-01-19 오후 7 04 49" src="https://user-images.githubusercontent.com/50910456/213414442-6e78f428-6943-41ec-beb2-e19734bf5f08.png">

- 뷰를 그리다가 제 능력부족으로 인해 조금 어거지로 짠 코드들이 중간중간 존재합니다… 😢 계속 작업하면서 수정해 나갈거지만 '왜 이렇게?' 하시는 부분이나 더 좋은 아이디어 있으면 마구 달아주세요..!! 😄

2023-01-20 15:28 UTC, seonyoung42 requested changes
성훈님 고생 많으셨습니다..👍🏻!!
필터뷰.. 진짜 힘드셨겠어요.. 보는데 약간 어지럽 ㅋㅋㅋㅋㅋ큐ㅠ 
고생많으셨고 설 연휴 잘 보내세요 ☺️!

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +        }
logo 와 searchIcon layout을 stackView로 잡으신 이유가 뭔지 궁금합니다.. !
그리고 navibar가 살아있어서 logoSearchStackView 상단 마진이 의도하신 것과 다르게 나오고 있어요! 
추가로 searchIcon 네이밍 대신 searchButton은 어떨까요?!

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> -
홈 뷰 스크롤 영역이 뷰 전체가 아니라 동네 리스트 부분만 스크롤이 되는게 맞나요? 동작이 어색한 것 같아서요 🥲🥲
만약 지금처럼 진행한다면 backView를 tableView headerview로 넣어서 backView까지 스크롤되도록 하는게 어떨까요?

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/InfraIconStackView.swift
> +                                          selectedImage: UIImage(named: "nature_selected") ?? UIImage())
성훈님 여기 아이콘이 선택될 때 스택 뷰의 레이아웃이 조금씩 바뀌어요 😂...ㅠㅠㅠㅠ 제 생각엔 필터 아이콘들 selected와 normal일때 이미지 크기가 다른 것 같은데 한 번 확인 부탁드립니당..!!

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionViewCell.swift
> +        searchCategoryBtn.configuration?.contentInsets.trailing = 12
```suggestion
        searchCategoryBtn.configuration?.contentInsets = NSDirectionalEdgeInsets(top: 0.0, leading: 12.0, bottom: 0.0,trailing: 12.0)
```
이렇게 한 줄로 작성하면 조금 더 간결하지 않을까 싶습니다..!

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionViewCell.swift
> +                                           selectedImage: UIImage(named: "arrowDown_selected") ?? UIImage())
성훈님 여기 isSelected 오버라이드 받아서 searchCategoryBtn의 tintColor를 바꿔주는게 더 깔끔하지 않을까 싶어요! 
이미지는 searchCategoryBtn.setImage(UIImage(named: "arrowDown")?.withRenderingMode(.alwaysTemplate) 이걸로 한번만 넣구요 !

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +
```suggestion
       var tempTraffic = "교통"
       if let first = tempModel.traffic.first {
            tempTraffic = tempModel.traffic.count == 1 ? first : first + " 외 \(tempModel.traffic.count - 1) 개"
        }
        
```
여기 코드를 이렇게 개선해보는건 어떨까용?!

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
> +    }()
여기 btnStackView를 사용하신 이유가 궁금합니다..!
introducebtn과 mapBtn의 가로 길이를 맞추고자함이면 equalWidth로 레이아웃을 잡는게 더 간편하지 않을까 싶어서요..!

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
> +                                          blur: 10.0, spread: 0, alpha: 0.4)
setupCell은 외부에서 cell에 데이터를 넣어줄때 사용하시는 메서드인 것 같아서 아래 속성 설정 코드들은 setupView로 가는게 더 좋지 않을까 싶어요!

2023-01-20 15:28 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionViewFlowLayout.swift
> +    }
여기 설정이 추가될 예정일까요?!
아니라면 FilterCollectionView에서 UICollectionViewFlowLayout 인스턴스 생성해서 바로 사용하는건 어떨까 싶어서요..!!

2023-01-20 18:03 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewModel.swift
> +            .disposed(by: disposeBag)
```suggestion
         self.input.infra
            .map { return ($0, $0 != "")}
            .bind { [weak self] in
                self?.tempFilterModel?.infra = $0.0
                self?.output.buttonsSelected.accept($0.1)
            }
            .disposed(by: disposeBag)
```
map에서 속성을 설정하는게 조금.. 어색한 것 같아서요! map에서 튜플로 넘겨주면 어떨까 싶어서 남겨봅니당..

2023-01-20 18:03 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
> +                self?.trafficCollectionView.deselectItem(at: indexPath, animated: true)
이 코드는 없어도 되지 않을까요?!

2023-01-20 18:03 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +            .disposed(by: disposeBag)
```suggestion
       viewModel?.output.searchFilterDataSource
            .observe(on: MainScheduler.instance)
            .bind(to: filterCollectionView.rx.items(cellIdentifier: FillterCollectionViewCell.reuseIdentifier,
                                                    cellType: FillterCollectionViewCell.self)) { index, item, cell in
                cell.setupCell(item, index)
            }
            .disposed(by: disposeBag)
```
이렇게 작성하면 dequeue를 작성하지 않아도 돼요..!!

2023-01-20 18:03 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
> +                                          blur: 10.0, spread: 0, alpha: 0.4)
cell 그림자가 피그마랑 달라서 봤더니 우선 shadowY값이 2에요!
그리고 그림자가 잘리고 있는데 HomeViewController에서 설정한 HomeViewController와 tableView 사이의 간격을 없애고 그 간격만큼 inset을 넣어주면 되지 않을까 싶어요..! 
```
contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 16, left: 16, bottom: 0, right: 16))
```

2023-01-21 06:05 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +        }
한줄에 있으면서 양쪽 끝에 붙어있는 모양을 가지면 저는 stackView를 종종 써서요..!! 따로따로 layout을 잡는거보다 stackView로 잡는게 편하더라구요.. 😅
상단 마진 그러네요.. 바로 수정했습니다 ㅠㅠㅠㅠㅠ 네이밍도 고쳤어요 ㅎㅎㅎ 👍

2023-01-21 06:06 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> -
이 부분 현재 디자이너님한테 여쭤본 상태입니다. 디자이너님이랑 한번 이야기 해보고 수정하도록 할게요..!! 😀

2023-01-21 06:21 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/InfraIconStackView.swift
> +                                          selectedImage: UIImage(named: "nature_selected") ?? UIImage())
제가 피그마에서 이미지를 잘못 추출했었네요.. ㅠㅠㅠ
근데 이부분 밑에서 선영님께서 말씀해주신 withRenderingMode(.alwaysTemplate) 방법으로 수정했습니다..! 👍

2023-01-21 06:21 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionViewCell.swift
> +        searchCategoryBtn.configuration?.contentInsets.trailing = 12
좋아요 좋아요 !!

2023-01-21 06:26 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionViewCell.swift
> +                                           selectedImage: UIImage(named: "arrowDown_selected") ?? UIImage())
이부분... 선영님께서 말씀해주신 방법이 좋아서 수정하려고 이것저것 해봤는데요..
text하고 dropdown 버튼만 색깔이 달라서 처리가 조금 힘들더라구요.. (제가 못하는 거 일지도..)
그래도 withRenderingMode(.alwaysTemplate) 이거 너무 좋은 거 같아서 적용할 수 있는 부분에는 앞으로 적용하겠습니다..! 👍

2023-01-21 06:26 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +
너무 좋습니다..!! 😆

2023-01-21 06:27 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
> +    }()
사실 이 부분도 맨 처음 stackView랑 느낌이 조금 비슷합니다.. 이렇게 생긴 뷰들은 stackView가 항상 먼저 생각이 나더라구요 ㅠㅠㅠㅠ 어느 부분이 더 좋은지 한번 고민해보겠습니다..!!

2023-01-21 06:28 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
> +                                          blur: 10.0, spread: 0, alpha: 0.4)
이동했습니다..!! ㅎㅎㅎ

2023-01-21 06:29 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionViewFlowLayout.swift
> +    }
처음에 따로 설정하는 부분들이 있었는데 수정하다보니 거의 없네요..
그래도 지금까지 CollectionView 관련해서는 따로 FlowLayout을 전부 만들었다보니 이대로 가도 괜찮지 않을까 싶습니다..!
또 설정이 더 추가될 수도 있으니까요..! 😄

2023-01-21 06:30 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewModel.swift
> +            .disposed(by: disposeBag)
오우.. 생각지도 못한 방법이네요.. 너무 좋습니다!

2023-01-21 06:36 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
> +                self?.trafficCollectionView.deselectItem(at: indexPath, animated: true)
![Simulator Screen Recording - iPhone 14 - 2023-01-21 at 15 34 06](https://user-images.githubusercontent.com/50910456/213847170-dbc1675c-6229-4ff3-8655-2cdb3cee4ade.gif)

itemDeselected 처리를 안해주면 button은 선택이 해제된 거 처럼 보이지만 실제로 데이터는 그렇지 않더라구요.. 그래서 저도 처음에는 itemSelected만 있는 줄 알아서 어떻게 하지 하다가 itemDeselected 이라는게 있길래 이걸로 처리하긴 했습니다..

2023-01-21 06:36 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +            .disposed(by: disposeBag)
박수 세번.. 👍

2023-01-21 06:38 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
> +                                          blur: 10.0, spread: 0, alpha: 0.4)
자세히보니 짤리네요.. 수정했습니다.. 감사합니다..!! 박수 다섯번.. 👍👍

2023-01-21 10:26 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> -
디자이너님이 뷰 전체를 스크롤해야한다고 하셔서 맞춰서 수정했습니다..!! 😀

2023-01-21 12:36 UTC, seonyoung42 approved these changes
성훈님 고생 많으셨습니다 !!
코멘트 드린 부분들이 작은 부분들이라 approve 했어요!

추가로 몇 가지 말씀드리고 싶은 부분이 있는데요 !
+  동네리스트 tableview를 위로 스크롤했을때 보이는 view.backgroundcolor가 tableview의 backgroundcolor와 동일하면 더 좋지 않을까 싶어서요 ! 
+ 파일 내부에서만 사용되는 메서드에 대해 private을 꼭 넣어주시고 있는 것 같은데요 (넘 좋다고 생각합니다👍🏻 !) private extension 안에 해당 메서드들을 작성하면 각 메서드에 private을 붙여주는 것과 같은 효과가 있다고 하더라구요! 이렇게 작성하면 코드 분리도 되고 private을 빼먹을 일도 없어서 좋은 것 같아 말씀드려봅니다 ☺️ !

2023-01-21 12:36 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +        stackView.setCustomSpacing(40, after: filterStackView)
오 stackView에 커스텀 스페이싱도 넣을 수 있었네요👍🏻 !!

2023-01-21 12:36 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +            .disposed(by: disposeBag)
성훈님 tableView도 위의 collectionView처럼 dequeue를 사용하지 않고 작성할 수 있어요 !

2023-01-21 12:36 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +
여기 피그마 보니까 텍스트가 '개' 가 아니라 '건' 이더라구요 !

2023-01-21 12:36 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
> +        mapBtn.setTitle("동네 지도", for: .normal)
여기도 setupView에 들어가면 더 좋지 않을까 싶어요 !

2023-01-21 12:38 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
> +                self?.trafficCollectionView.deselectItem(at: indexPath, animated: true)
에고 당연히 데이터도 deselected 될거라고 생각했네요 😰😰

2023-01-21 14:54 UTC, llghdud921 requested changes
성훈님 진짜 Home화면 너무 잘짜셨네요...... 미쳤다 우리팀.....🥹
정말 고생많으셨습니다ㅠㅠ

> 바텀시트를 사용하실 때 dismiss를 따로 줘버리면 애니메이션이 이상하더라구요. 살펴보니 BaseBottomSheetViewController에 setBottomSheetStatus를 사용하면 될 거 같아 테스트해봤더니 자연스럽게 dismiss 처리됩니다..! 바텀시트 사용하시는 분들은 이렇게 사용하시면 될 거 같아요~~ 😆

제가 구현한 시트가 이상했던 이유가 이거였군요..... 진작 여쭤볼걸 그랬네요,,ㅎㅎ

---

<img src="https://user-images.githubusercontent.com/40068674/213872394-4f97d4b6-95a0-434e-aa43-1c23bfe4ba49.png" height="816" width="327">

iphone8 시뮬인데 bottomSheet가 짤립니다ㅠㅠ
sheet처럼 크기를 지정하는 뷰는 screenwidth를 이용해서 조절해서 높이를 정해줘야합니당

2023-01-21 14:54 UTC, llghdud921 commented on FindTown/FindTown/Presentation/HomeScene/Flows/FilterSheetCoordinator.swift
> +        guard let navigationController = navigationController else { return }
이전 뷰컨에 모델을 넘겨주는 방식을 고민하고 있었는데 이렇게 해결하셨군요!!
참고해보겠습니다!!
네트워크 후에 개선할 예정인데 parentCoordinator를 가지고 있는 방식으로도 생각해보고있습니다ㅎㅎ

2023-01-21 14:54 UTC, llghdud921 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +                withAttributes: [NSAttributedString.Key.font : UIFont.systemFont(ofSize: 14)]
크기를 직접 계산하는 방식으로 구현하셨네요 👍👍
혹시 autoSize 사용하지 않으신 이유가 무엇인지 여쭤볼수있을까요... (진짜 궁금해서 물어봅니다)

2023-01-21 14:54 UTC, llghdud921 commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
> +                self?.viewModel?.input.traffic.onNext(self?.selectedCellsString ?? [])
엄청난 작업이네요.... 굿

2023-01-21 14:54 UTC, llghdud921 commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/InfraIconStackView.swift
> +}
프로토콜내 objc 메소드가 있으면 해당 프로토콜도 objc로 만들어야한다는것을 처음 알았어요!!!!
덕분에 공부하게 됩니다~!

2023-01-21 14:54 UTC, llghdud921 commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/InfraIconStackView.swift
> +        delegate?.didSelectInfraIcon?(value: button.titleLabel?.text ?? "")
성훈님 코드가 이렇게 Nil-Coalescing Operator를 많이 사용하시는데 이렇게되면 문제가 발생했을때 디버깅하기 어려워요ㅠㅠ
가능한 guard 구문을 이용해서 lldb로 오류를 찾게끔 코드를 구성해주시면 감사하겠습니다!

2023-01-23 05:40 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +            .disposed(by: disposeBag)
너무 좋습니다..!! 👍

2023-01-23 05:41 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
> +        mapBtn.setTitle("동네 지도", for: .normal)
수정했습니다!! ㅎㅎㅎㅎ

2023-01-23 05:45 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +                withAttributes: [NSAttributedString.Key.font : UIFont.systemFont(ofSize: 14)]
계속 CGSize를 지정안해주면 collectionView auotlayout 경고가 계속 뜨더라구요 ㅠㅠㅠㅠ 
그리고 leading, trailing 12만큼 크기가 들어가야하는데.. 제 능력부족으로 직접 계산하는 방법 말고는 해결책을 찾지 못했습니다.. ㅠㅠㅠㅠ

2023-01-23 05:59 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/InfraIconStackView.swift
> +        delegate?.didSelectInfraIcon?(value: button.titleLabel?.text ?? "")
그렇군요..!! 생각없이 막 사용했던게 이런 문제점을 발생할 수 있다니.. 메모.. 😅

2023-01-23 13:49 UTC, llghdud921 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
> +                withAttributes: [NSAttributedString.Key.font : UIFont.systemFont(ofSize: 14)]
autosize가 layout 경고가 뜨긴 하더라구요.....
이부분 우선 구현하고 어떤 방식으로 구현할지 회의를 통해 논의해봅시다!!

2023-01-23 13:49 UTC, llghdud921 approved these changes
🍎🎉

2023-01-23 14:30 UTC, merged