홈 검색 UI 구현
YAPP-Github/21st-iOS-Team-1-iOS pull request #53
Opened 2023-01-25 05:08 UTC by ungchun

## Motivation
- issue number : #37 

## Changes
- 검색 UI 구현
- UIAlertController popup extension 추가

## Screen Shots
![Simulator Screen Recording - iPhone 14 - 2023-01-25 at 13 21 22](https://user-images.githubusercontent.com/50910456/214479596-a4293167-353d-48bf-a880-897e95b6123a.gif)

## To Reviewers
- 검색창이 사라지니 일이 엄청 줄어드는군요.. 허허; 😄
- GuSelect, GuSelectDong 네이밍이 고민입니다.. 피그마 보고 우선 이름을 이렇게 지었는데.. 더 좋은 네이밍이 있다면 추천받습니다 ㅠㅠㅠㅠ
- UIAlertController popup이 폰트 색깔만 변경이 가능해서 디자이너님한테 말씀드렸고 이대로 진행하자고 하셨습니다..! 😀
- 최근 검색한 동네 네트워크 들어오면 10개 제한, 중복처리하면 될 거 같습니다..! 👍
- 많은 피드백 바랍니다..!! 😄

2023-01-25 07:56 UTC, seonyoung42 approved these changes
성훈님 고생많으셨습니다 👍🏻!
네이밍만 변경하면 될 것 같아 미리 approve 했어요!

2023-01-25 07:56 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/GuSearch/GuSelect/GuSelectViewController.swift
> +    private let allRemoveLabelTapGesture = UITapGestureRecognizer()
allRemoveLabelTapGesture보다는 removeEveryLabelTapGesture은 어떨까요? 동사가 제일 서두로 가는게 좋을 것 같아요.!

2023-01-25 07:56 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/GuSearch/GuSelect/GuSelectViewController.swift
> +final class GuSelectViewController: BaseViewController {
countyCollectionView의 county가 자치구를 의미하는게 맞을까요??.. 자치구를 Gu, County 두 가지로 네이밍하고 있는 것 같아서 둘 중 하나로 통일하는게 어떨까 싶어요.. ! 그리고 SelectGu(County)ViewController 는 어떠신가요..핳

2023-01-25 08:21 UTC, llghdud921 requested changes
선영님과 같은 의견으로 네이밍 변경이 필요해보이구요!!
제가 찾았을때는 County가 자치구를 의미해서 Gu로 된것을 County로 변경해야할 것 같아요 

그리고 검색 UI는 아니지만.. 홈 화면의 로고와 검색 버튼이 navigationItem내에 있는 것 같아요 유미님께 확인해보고 수정해주시면 감사하겠습니다!

2023-01-25 09:24 UTC, llghdud921 commented on FindTown/FindTown/Presentation/HomeScene/Flows/GuSearchCoordinator.swift
> +                                                                    selectGuData: selectGuData)
늦게 댓글달아 죄송합니다..ㅠㅠ
selectGuData를 viewModel에 넣어서 바인딩 시키는게 더 맞을것같아요!!

2023-01-25 16:32 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/GuSearch/GuSelect/GuSelectViewController.swift
> +    private let allRemoveLabelTapGesture = UITapGestureRecognizer()
오오 좋아요.. 수정했습니다..!!

2023-01-25 16:33 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/GuSearch/GuSelect/GuSelectViewController.swift
> +final class GuSelectViewController: BaseViewController {
감사합니다 ㅠㅠㅠㅠ.. 네이밍 너무 어려워요..

2023-01-25 16:37 UTC, ungchun commented
- 전체적인 네이밍 추천해주신대로 수정했습니다.. 너무 감사드려요.. 👍 (저 네이밍.. 절대 대충하지 않았어요..ㅠㅠㅠㅠㅠㅠ)
- Gu 관련해서 전부 County로 수정했습니다!!
- 호영님께서 말씀해주신게 맞더라구요.. navigationItem에 들어가야하는게.. 알려주셔서 너무 감사합니다.. 디자이너님께서 로고가 어떻게 완성되냐에 따라서 search button이 수정될 수도 있다고 하셔서 만약 수정이 된다면 그때 수정할 예정입니다..!! 😀

2023-01-26 05:53 UTC, llghdud921 approved these changes

2023-01-26 09:08 UTC, seonyoung42 approved these changes
고생하셨습니다 👍🏻!!

2023-01-26 09:30 UTC, merged