동네소개 UI 구현
YAPP-Github/21st-iOS-Team-1-iOS pull request #57
Opened 2023-01-29 14:40 UTC by seonyoung42

## Motivation
- issue number : #56 

## Changes
- 동네소개 화면구현(탭맨 영역 제외)
- Traffic enum 타입에 shortDescription 추가
- TownMood enum 타입 생성 

## Screen Shots
<img width="259" alt="스크린샷 2022-12-28 오후 3 07 33" src="https://user-images.githubusercontent.com/77603632/215333741-4c0852f6-88ba-4376-a911-6f127ca04f0e.png">

## To Reviewers
+ 동네 소개 페이지는 데이터를 어떻게 대응해서 뿌려줄지가 중요해서 피드백 받고자 조금 일찍 pr 올려봅니다 !
   + 실제 서버에서 받는 데이터 형식이랑 거의 유사하게 TownIntroViewModel 하단에 임시데이터를 만들어 놓았습니다 !
+ 동네 분위기 케이스가 너무 많아서 네이밍을 walking1, walking2,, 이렇게하는 대신 해당 케이스를 누르면 한글네이밍을 볼 수 있도록 위에 주석을 달아줬어요 괜찮을까요?🥹
+ 숫자로 보는 동네의 경우엔 해당 텍스트에 대응하는 타입을 만들어주는게 큰 의미가 없을 것 같아 지금처럼 구현해놓았는데 혹시 다른 의견 있으시다면 환영입니다..!

2023-01-29 16:20 UTC, llghdud921 requested changes
선영님! 고생많으셨어요!!

데이터들 관리하는게 이렇게 힘들줄 몰랐네요..ㅠㅠ 아마 서버랑 이야기를 많이 해봐야하지 않을까 싶습니다

그리고 현재 TownInfo가 Favorite내에 있는데 Home에서도 사용하니까 TownInfoScene으로 따로 폴더 분리하는 것은 어떨까 싶습니다!

2023-01-29 16:20 UTC, llghdud921 commented on FindTown/FindTown/Presentation/FavoriteScene/Favorite/TownIntro/SubViews/TownMoodCollectionView/TownMoodCollectionViewCell.swift
> +            self.backgroundColor = UIColor(red: 248, green: 244, blue: 243)
이모지 포함 텍스트랑 color는 enum에 정의하면 될 것 같습니당

2023-01-29 16:20 UTC, llghdud921 commented on FindTown/FindTown/Presentation/FavoriteScene/Favorite/TownIntro/SubViews/TrafficTip/TrafficTipView.swift
> +        }
이것도 traffic enum에 넣으면 될 것 같습니다!

2023-01-29 16:20 UTC, llghdud921 commented on FindTown/FindTown/Domain/Entities/TownMood.swift
> +    case infra3
네이밍이 참 애매하네요ㅠㅠ 
아니면 서버하고 협의해서 string이랑 색상코드 내려달라고 하는것도 괜찮을 것 같아요!

2023-01-29 16:20 UTC, llghdud921 commented on FindTown/FindTown/Presentation/FavoriteScene/Favorite/TownIntro/SubViews/TownRank/TownRankView.swift
> +            rightTextLabel.text = "\(data.1)"
test들을 enum 값으로 정의만 하면 괜찮을 것 같습니다!
서버에서 어떻게 내려올지 감이 안잡혀서.. 한번 여쭤보시는것도 좋을 것 같아요!

2023-01-29 16:20 UTC, llghdud921 commented on FindTown/FindTown/Presentation/FavoriteScene/Flows/FavoriteCoordinator.swift
> +        navigationController.pushViewController(TownIntroViewController(viewModel: TownIntroViewModel()), animated: true)
요렇게 따로빼서 관리하는것이 더 좋을 것 같아요!! SigninCoordinator 참고해주세용 ☺️
```
internal func signUpInputLocationAndYearsScene(_ signupUserModel: SignupUserModel) -> UIViewController {
        let locationAndYearsViewModel = LocationAndYearsViewModel(delegate: self, signupUserModel: signupUserModel)
        let locationAndYearsViewController = LocationAndYearsViewController(viewModel: locationAndYearsViewModel)
        return locationAndYearsViewController
    }
```

2023-01-30 04:43 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/FavoriteScene/Favorite/TownIntro/SubViews/TownMoodCollectionView/TownMoodCollectionViewCell.swift
> +            self.backgroundColor = UIColor(red: 248, green: 244, blue: 243)
앗 그렇네요 !!

2023-01-30 04:44 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/FavoriteScene/Favorite/TownIntro/SubViews/TrafficTip/TrafficTipView.swift
> +        }
좋습니당 !!! 왜 코드짤땐 생각이 안났을까요 🥹🥹🥹

2023-01-30 04:53 UTC, seonyoung42 commented on FindTown/FindTown/Domain/Entities/TownMood.swift
> +    case infra3
텍스트만 알면 enum타입으로 변환해서 스트링과 색상을 적용할 수 있으니까 서버에 스트링과 색상을 요청할 필요는 없지 않을까요?!  스트링에 이모지도 들어가야하는 상황이라.. 앱단에서 처리하는게 더 효율적일 것 같다고 생각이 듭니당 🥲

2023-01-30 05:00 UTC, llghdud921 commented on FindTown/FindTown/Domain/Entities/TownMood.swift
> +    case infra3
그렇군요! 그러면 서버에서 어떻게 내려주실지 여쭤본다음에 네이밍을 개선해도 괜찮을 것 같아요! 
자치구, 동처엄 코드로 내려주실수도 있어서요!!

2023-01-30 05:07 UTC, ungchun commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewController.swift
> +        self.view.backgroundColor = FindTownColor.grey1.color
```suggestion
    override func setupView() {
        self.stackView.backgroundColor = FindTownColor.grey1.color
```

전체 view의 backgroundcolor를 세팅을 하셔서 scroll 했을 때 여백까지 grey로 보여요..! 이렇게 하시면 원하시는 화면이 나오는 것 같습니다..! :)

2023-01-30 05:13 UTC, ungchun commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewController.swift
> +    private let townRankInfoImageView = UIImageView()
이 부분 뭔가 생긴게 전형적인 컬렉션 뷰 처럼 생겨서 아마 저라면 컬렉션 뷰로 접근했을 거 같은데, ScrollView + StackView로 구현하셨군요..!! 

혹시 이렇게 구현하신 이유가 이거 때문인가용..?
> 숫자로 보는 동네의 경우엔 해당 텍스트에 대응하는 타입을 만들어주는게 큰 의미가 없을 것 같아 지금처럼 구현해놓았는데 혹시 다른 의견 있으시다면 환영입니다..!

아니면 따로 있으실까요..?! (정말 궁금해서 여쭤봅니다..!)

2023-01-30 05:17 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewController.swift
> +        self.view.backgroundColor = FindTownColor.grey1.color
앗 그렇네요 감사합니다 !!

2023-01-30 05:19 UTC, ungchun reviewed
선영님..! 고생많으셨습니다..!! :)
동네 소개페이지 데이터 맵핑할 게 엄청 많네요.. 한두개가 아닌데.. 

저도 호영님 말씀처럼 TownInfoScene으로 따로 폴더 분리하는게 더 좋아보여요..! + Coordinator 👍
나머지는 호영님이랑 거의 겹쳐서 코멘트만 확인해주시면 될 것 같습니다..!! 😀

2023-01-30 05:20 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/FavoriteScene/Favorite/TownIntro/SubViews/TownRank/TownRankView.swift
> +            rightTextLabel.text = "\(data.1)"
동네 지수들은 통일된 형식이 아니라서 enum으로 정의하지 않았는데 따로 빼니까 더 깔끔하네요 👍🏻 !

2023-01-30 05:25 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewController.swift
> +    private let townRankInfoImageView = UIImageView()
아 숫자로 보는 동네의 뷰를 처음엔 항목별로 각각 만들어 두려고 했었어요! 코드로 가로스크롤+스택뷰를 구현해보고 싶기도 했구요...😅 저도 만들고 보니 컬렉션뷰로 할껄 싶긴 했지만ㅋㅋ 스크롤 뷰에 들어가는 뷰 갯수가 최대 7개라 큰 문제가 없을 것 같아 이렇게 진행했어요 !

2023-01-30 13:03 UTC, seonyoung42 commented
말씀주신 enum 타입 정의와 TownIntro 분리 및 coordinator 생성해서 다시 재리뷰 요청합니다 ☺️!

2023-01-30 16:35 UTC, ungchun approved these changes
선영님..! 고생하셨습니다 :)

TownMood enum은 진짜 좀 고민이긴하네요..
서버쪽에서 데이터를 어떻게 내려줄 지..

탭맨 작업하실 때 연락주세요..!! 😀

2023-01-31 01:59 UTC, llghdud921 approved these changes
선영님 고생많으셨습니다!

2023-01-31 05:27 UTC, merged