마이 페이지 구현
YAPP-Github/21st-iOS-Team-1-iOS pull request #62
Opened 2023-02-02 09:47 UTC by ungchun

## Motivation
- issue number : #50 

## Changes
- HomeView 구조 변경
- BaseBottomSheet .hide 수정
- 2개의 버튼을 가지는 popup 추가
- MyPage Scene 구현

## Screen Shots
![Simulator Screen Recording - iPhone 14 - 2023-02-02 at 17 54 53](https://user-images.githubusercontent.com/50910456/216277161-4ae73ce8-223a-4dd5-a063-d0caa036286a.gif)

![image](https://user-images.githubusercontent.com/50910456/216280087-92d0ed66-9e1e-4339-b9a2-47b91b8d158b.png)

<img width="868" alt="스크린샷 2023-02-02 오후 5 19 49" src="https://user-images.githubusercontent.com/50910456/216280300-ddd0b78a-4257-4a99-aadb-1797b2d2952b.png">

<img width="469" alt="스크린샷 2023-02-02 오후 3 51 33" src="https://user-images.githubusercontent.com/50910456/216280320-02b530cc-9ca3-4ba4-8c69-8883c41b6115.png">

## To Reviewers
- 우선 사과의 말씀을 드립니다.. 생각보다 코드의 양도 많고 정리도 완벽하게 하지는 못했습니다.. ㅠㅠㅠㅠㅠㅠㅠ 오늘 내일 계속 수정할 예정인데, 양이 꽤 많고 피드백을 미리 받고 싶어서 PR 올려요..!!
- Home View에서 테이블 뷰 페이지네이션 구현하다가.. 데이터를 추가로 불러오면 tableView에 scroll하고 scrollView가 계속 이상하게 꼬이더라구요.. 그래서 tableView Header를 사용해서 구조 수정했습니다..!! 😀
- 2개 버튼을 가지는 popup 추가했습니다..! 사용법은 self.showAlertSuccessCancelPopUp 하시고 필요한 값들을 넣으시면 됩니다..!!
기본적으로 message(제목 밑에 택스트)는 필요하시면 넣으시면 되고 필요없으시면 안넣으셔도 됩니다. 마찬가지로 cancel action 또한 기본 dismiss가 들어가있고 만약 취소 버튼에 특별한 action이 필요하시면 값을 추가해주시면 됩니다..! 😎
- MyPage CollectionView에서 UICollectionViewCompositionalLayout를 사용했습니다..! 저도 처음써보는 친구입니다.. CompositionalLayout은 item -> group -> section 으로 구성이 되는데 현재 마이페이지에서는 topHeader, support, info 총 3개의 섹션으로 구성되어 있습니다. topHeader는 최상단에 있는 유저정보, 닉네임수정, 리뷰보기가 포함된 뷰이고 cell은 가지지 않고 footerView로 뷰를 구성했습니다. support 지원, info 정보의 item을 표시하고 각 headerView(divider)를 가지고 있는 형태입니다. 어찌어찌 뷰는 그리고 기능도 완성은 했습니다만.. dataSource 처리를 rx로 하고 싶었는데 이 layout으로 어떻게 해야하는지.. 계속 고민해 보겠습니다..
- 회원 정보 불러오는 건 위에 이미지처럼 정상적으로 닉네임을 받아오는 거 까지 확인했습니다. 그 과정에서 Berear 오타를 발견해 Bearer로 수정했습니다 ㅎㅎㅎ. 회원정보를 불러오고 닉네임, 어디 살고 얼만큼 살았는지 표시하는 로직은 조금 더 생각을 해봐야할 거 같고 추후에 익명으로 들어왔을 때 처리랑 같이 수정하겠습니다..! 😀
- 닉네임 중복확인도 response 수정했고 소소하게 테스트도 넣어봤습니다.. 닉네임 변경은 아직 불가능하고 중복확인까지만 가능한 상태입니다.
- 내 정보 불러오는 repository, usecase, request, response 모두 User 라는 이름으로 붙여서 만들었는데 이렇게 가도 될까요..?? member가 있기도 하고 애매하네요 ㅠㅠㅠㅠ 위치도 한번 봐주시면 감사하겠습니다.. 
- 지금 MyPageScene에 Tests라고 만들어 놓고 테스트 코드를 넣었는데 이렇게 유닛 테스트들을 씬 별로 추가하는게 나을까요?? 🤔

- 계속 수정하면서 push 올리겠습니다 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ... 화이팅...

2023-02-02 16:05 UTC, llghdud921 requested changes
성훈님 
코드에 대해 궁금한 점 위주로 댓글 남겼습니다!

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Data/Requests/User/UserInfomationRequest.swift
> +    init(HTTPHeaders: HTTPHeaders) {
정확하게 이해하고 사용하셨네요 👍

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Data/Requests/User/UserInfomationRequest.swift
> +struct UserInfomationRequest: BaseRequest {
저는 Data layer는 api 쪽에 가깝다고 생각해서 서버에서 구현해주신 naming인 member를 이용해서 구현을 했어요

성훈님이 편하신대로 구현하시는게 좋을것 같은데 저희 생각은 user, member 둘 중 하나로 가야할 것 같습니다

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MyPageScene/Tests/MyPageTests.swift
> +final class MyPageTests: XCTestCase {
이건 테스트파일로 빼야해요 

FindTownTests내 폴더 만들어서 분리해야합니당

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MyPageScene/Tests/MyPageTests.swift
> +//@testable import FindTown
주석은 제거하는게 좋지 않을까요? ☺️

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTownNetwork/Sources/FindTownNetwork/Http/HTTPHeader.swift
> +        return HTTPHeader(name: .authorization, value: "Bearer \(bearerToken)")
아이쿠.. 감사합니다ㅎㅎ

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTownCore/Sources/FindTownCore/Base/BaseBottomSheetViewController.swift
> -            })
이거 일부러 뺀건데요..ㅠㅠ 비동기 처리할때 로직이 꼬여요

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MyPageScene/DemoMyPageEntitie/Section.swift
> +enum MyPageDemoData {
이거 네이밍이 왜 데모가 들어가나요?

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/SupprotSectionCollectionViewCell.swift
> +final class SupprotSectionCollectionViewCell: UICollectionViewCell {
오타발견입니다!!

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/MyPageCollectionViewCompositionalLayout.swift
> +            }
여기서 datasource를 가져오는 부분이 비효율적이라고 생각해요..
그냥 sectionNumber 이용해서 분기처리하는 것이 좋을 것 같습니다 아니면 allcase를 사용하는 것도 좋겠네요

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/MyPageCollectionViewCompositionalLayout.swift
> +private extension MyPageCollectionViewCompositionalLayout {
compositional 핵심로직.. 좋네요 👍

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/CollectionHeaderView.swift
> +    private let dongPeriod = FindTownLabel(text: "신림동 거주, 2년 6개월", font: .label1, textColor: .grey6)
저희 dong은 village 네이밍으로 가기로 했는데 계속 dong으로 쓰시네요ㅠㅠ

2023-02-02 16:05 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/InfoSectionCollectionViewCell.swift
> +            break
delegate를 사용하지 않고 tapGesture를 이용하신 이유가 무엇인가요?

2023-02-03 04:12 UTC, llghdud921 commented on FindTown/FindTownUI/Sources/FindTownUI/PopUp/AlertSuccessCancelPopUpViewController.swift
> +public class AlertSuccessCancelPopUpViewController: UIViewController {
이거 네이밍도 다시 해야할 것 같습니다..

2023-02-03 07:08 UTC, ungchun commented on FindTown/FindTown/Data/Requests/User/UserInfomationRequest.swift
> +struct UserInfomationRequest: BaseRequest {
서버에서 정해준 네이밍이 기준이 되는게 좋네요..! 기존 user에서 member로 맞췄습니다..!!

2023-02-03 07:09 UTC, ungchun commented on FindTown/FindTown/Presentation/MyPageScene/Tests/MyPageTests.swift
> +final class MyPageTests: XCTestCase {
MyPageScene 하나 만들어서 추가했습니다 :)

2023-02-03 07:09 UTC, ungchun commented on FindTown/FindTown/Presentation/MyPageScene/Tests/MyPageTests.swift
> +//@testable import FindTown
이건 진짜 좀 부끄럽네요...

2023-02-03 07:10 UTC, ungchun commented on FindTown/FindTownCore/Sources/FindTownCore/Base/BaseBottomSheetViewController.swift
> -            })
그렇군요.. 한번 여쭤보고 수정할 걸 그랬습니다.. 우선 되돌려놨습니다..!!

2023-02-03 07:30 UTC, ungchun commented on FindTown/FindTown/Presentation/MyPageScene/DemoMyPageEntitie/Section.swift
> +enum MyPageDemoData {
허허.. 잠시 만들어놓는다는게.. 수정했습니다..!!
추가로 demo를 붙여놓은 데이터들이 조금 있는데 네트워크 붙이고 한번에 삭제하겠습니다..! :)

2023-02-03 07:33 UTC, ungchun commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/MyPageCollectionViewCompositionalLayout.swift
> +            }
그러네요.. datasource를 가져올 필요가 없네요... sectionIndex 사용해서 분기처리했습니다..! 감사합니다 :)

2023-02-03 07:34 UTC, ungchun commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/CollectionHeaderView.swift
> +    private let dongPeriod = FindTownLabel(text: "신림동 거주, 2년 6개월", font: .label1, textColor: .grey6)
아이고.. dong이라고 적혀있는 네이밍 전부 village로 수정했습니다.. ㅠㅠㅠㅠ 😢

2023-02-03 07:50 UTC, ungchun commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/InfoSectionCollectionViewCell.swift
> +            break
처음에 cell에서 직접 처리하는 방법밖에 돌아가지 않아서.. delegate는 생각하지 못했었고, tapGesture라도 써야겠다.. 라고 생각을 했습니다.. 😢 근데 코드를 조금 수정을 했고 MyPageViewController에서 navigate 처리하도록 했습니다..! 😀

2023-02-03 08:06 UTC, ungchun commented
코드 진짜 보기 힘들었을텐데.. 꼼꼼히 봐주셔서 감사합니다..!! 👍
코멘트 주신 부분들은 수정을 했습니다..! 😀

2023-02-03 08:32 UTC, llghdud921 requested changes
굿뜨굿뜨

compositional layout 처음 도전인데 정말 잘하시는것같아요!!!!
저도 많이 배웠습니다ㅎㅎ

2023-02-05 04:16 UTC, llghdud921 approved these changes

2023-02-05 06:30 UTC, seonyoung42 approved these changes
성훈님 고생 많으셨습니다 !!
호영님께서 코멘트를 많이 주셔가지고 저는 따로 드릴게 없었어요 !! (리뷰가 넘 늦어져서 진짜 죄송해요.ㅠㅠㅠ)
그리고 CompositionalLayout 너무 멋져요 👍🏻👍🏻 다음에 유사한 화면을 작업하게되면 참고할 것 같아요 !!

2023-02-05 06:30 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/SubViews/ReviewTableViewCell.swift
> +        introduce.attributedText = attrString
성훈님 여기도 행간 설정하는 부분 같은데 setLineHeight를 사용해도 되지 않을까요?! 조금 다른가용??

2023-02-05 06:30 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewController.swift
> +//  MyPageViewController.swift
성훈님 이 파일의 if let var {} 문법 네 개 혹시 if let var = var {} 로 바꿔주실 수 있을까요...🥲🥲🥲..죄송해요ㅠㅠㅠㅠ

2023-02-05 06:50 UTC, ungchun commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/SubViews/ReviewTableViewCell.swift
> +        introduce.attributedText = attrString
저게 있었군요.. 안쓰다가 이번에 쓰게 됐네요.. 수정했습니다!! :)

2023-02-05 06:50 UTC, ungchun commented on FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewController.swift
> +//  MyPageViewController.swift
수정했습니다~

2023-02-05 06:52 UTC, merged