동네 지도에 행정동 좌표 나타내는 기능
YAPP-Github/21st-iOS-Team-1-iOS pull request #71
Opened 2023-02-13 16:07 UTC by llghdud921

## Motivation
- issue number :  #23 

## Changes
- 동네 지도에 행정동 경계가 나타나도록 기능을 구현하였습니다

## Screen Shots

![Simulator Screen Recording - iPhone 14 Pro - 2023-02-14 at 01 09 06](https://user-images.githubusercontent.com/40068674/218510494-d241d448-1552-4d62-a6aa-14d7547787cd.gif)

## To Reviewers
- 행정동 테마 지도까지 띄우길 바랬지만 responseData를 변경해주신다하여 좌표만 먼저 PR올립니다 총총총
- 현재 동을 선택하면 해당 동으로 이동하고 좌표는 나오지만 중심점이 아닙니다..ㅠ 중심좌표도 내려달라고 요청드렸어요.. 추후에 수정하겠습니다
- 인프라, 테마 지도 관련해서도 약간 구현하였는데 생각하던 포맷이랑 너무 달라서 기존 타입들을 정리해야할것같아요 임시로 MCategory 이렇게 네이밍을 했습니다ㅎㅎ 
- 그리고 서울경계만 회색으로 칠하려고 했는데 서울 경계에 있는 동(가양동)이 이상하게 보여서 경기도도 칠해버렸어요!ㅎㅎ
- MapConstants에 데이터들을 넣어놓았는데 괜찮은지 한번 봐주세요.. 뷰컨 코드가 너무 길어져서 분리했는데 이게 맞는지 모르겠습니다ㅠㅠ

2023-02-13 18:55 UTC, ungchun commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
> +                    self.output.cityBoundaryCoordinates.onNext(villageLocaionInformation.coordinate)
이거 좌표까지 같이 처리하려니 과정이 어마어마하네요.. 👍

2023-02-13 18:55 UTC, ungchun commented on FindTown/FindTown/Domain/Enumerations/InfraCategory.swift
> +    case security
진짜 지도 데이터 관리하기 너무 어려운 것 같아요... 👍😢

2023-02-13 19:12 UTC, ungchun commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +//            self.detailCategoryView.setStackView(data: item.detailCategories)
요 친구 나중에 쓰시나용??

2023-02-13 19:24 UTC, ungchun requested changes
호영님..! 고생하셨습니다..!! 아무리봐도 맵이 진짜 힘든 것 같아요.. 😀👍 

- 맵 처음 들어갈 때 setCity cityCode nil 로 들어가서 500 에러가 뜨더라구요..! 알고 계실 것 같긴 하지만.. 혹시나 싶어서 적어봅니다.. 😅

- 카메라 영역 제한이 필요해 보입니다!! 네이버 지도에서는 카메라 영역 제한을 할 때 줌 레벨도 같이 설정을 하라고 가이드를 하고 있어요! 밑에 예시 코드로 서울 인근 카메라 영역하고 줌 레벨 적어놓을게요!!
<img width="320" alt="스크린샷 2023-02-14 오전 4 00 28" src="https://user-images.githubusercontent.com/50910456/218549750-8a5eb48e-7680-4c54-89e7-16a8216ac636.png">

```
mapView.minZoomLevel = 10.0
        
// 서울 인근 카메라 제한
mapView.extent = NMGLatLngBounds(southWestLat: 37.40, southWestLng: 126.70, northEastLat: 37.60, northEastLng: 127.10)
```

- MapConstants 부분 대한민국 한반도 지역을 칠하지 않고 서울, 경기를 따로 따로 칠하신 이유가 있을까요..?? 대한민국 좌표를 넣으면 MapConstants 코드가 훨씬 줄어들 것 같아서요..!! 그러면 ViewController에서도 polygonOverlay 1개로 처리가 가능한 것 같습니다! 😀

```
// MapConstant
private static let koreaBoundaryCoordinates = [[39.327518, 124.517393], [39.588436, 128.985682], [35.251701, 131.426344], [33.218602, 124.799008], [39.327518, 124.517393]]

static var koreaBoundaryPointsForPolygon: [NMGLatLng] {
    return self.koreaBoundaryCoordinates.map { coordinate in
        NMGLatLng(lat: coordinate[0], lng: coordinate[1])
    }
}

// MapViewController
let interiorRingsCoordinates = boundaryCoordinates.map { coordinate in
    NMGLatLng(lat: coordinate[1], lng: coordinate[0])
}
let villagePolygon = NMGPolygon(ring: NMGLineString(points: MapConstant.koreaBoundaryPointsForPolygon), interiorRings: [NMGLineString(points: interiorRingsCoordinates)])
villagePolygonOverlay = NMFPolygonOverlay(villagePolygon as! NMGPolygon<AnyObject>)

villagePolygonOverlay?.fillColor = UIColor(red: 26, green: 26, blue: 26).withAlphaComponent(0.2)
villagePolygonOverlay?.mapView = mapView
```

- 네이버 지도에서는 레이어 그룹을 2개 이상 활성화 할 수 있어요! 대중교통 그룹이라던지 등산로 그룹이라던지 등등.. 제 생각에는 대중교통 + 건물 or 등산로 이렇게 가는게 제일 무난하지 않을까 생각이 들긴 합니다만.. 호영님이 문서보시고 판단하셔도 될 것 같아요!

```
mapView.setLayerGroup(NMF_LAYER_GROUP_MOUNTAIN, isEnabled: true)
mapView.setLayerGroup(NMF_LAYER_GROUP_TRANSIT, isEnabled: true)
```

2023-02-14 05:45 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +//            self.detailCategoryView.setStackView(data: item.detailCategories)
넵 데이터 내려오고 사용하려구요ㅠㅠ
지금 포맷이 너무 바뀌어서 우선 주석처리 했습니다

2023-02-14 06:04 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
> +                    self.output.cityBoundaryCoordinates.onNext(villageLocaionInformation.coordinate)
하 이거 코드 너무 더럽죠.. 머리아프다..... 🤦‍♀️

2023-02-14 06:31 UTC, llghdud921 reviewed
성훈님! 정말 감사합니다!! 비루했던 뷰들이 조금 나아졌네요...ㅎㅎ

- 말씀하신대로 카메라 영역 제한, 레이어 그룹을 설정 했습니다! 생각도 못했네요ㅎㅎ 

>네이버 지도에서는 카메라 영역 제한을 할 때 줌 레벨도 같이 설정을 하라고 가이드를 하고 있어요! 밑에 예시 코드로 서울 인근 카메라 영역하고 줌 레벨 적어놓을게요!!

요거는 어디에 나와있나요? 

>MapConstants 부분 대한민국 한반도 지역을 칠하지 않고 서울, 경기를 따로 따로 칠하신 이유가 있을까요..??

이건 줌레벨을 제한하는 방법을 모른상태로 크게 줌을 하게 되면 앱의 완성도가 떨어져보일수도 있다는 우려를 했습니다.. 그래서 경기까지 칠해버렸구요..ㅠㅠ 근데 줌레벨을 제한함으로써 문제가 해결되었네요!! 👍

2023-02-14 06:34 UTC, seonyoung42 reviewed
호영님..!! 고생 많으셨어요 !!
지도 정말.. 어렵네요 🥹🥹
동 별로 전부 확인은 못했지만 아래 두 동 한 번 확인해봐 주시면 좋을 것 같아요..!
+ 강서구-가양동 => 레이어 확인 필요(부분 부분 끊김?...ㅠㅠ)
+ 강남구-논현동 => 양재동으로 뜸, 레이어 확인필요(겹침)

그리고 혹시 camera가 이동될 때 중심점이 해당 동의 중심이긴 어려울까요? 아니면 zoom 레벨을 낮추는 것도 괜찮지 않을까싶어요..!

2023-02-14 06:34 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +
호영님 찾아보니까 NMFCameraUpdate 객체에서 animation을 제공하더라구요! 애니메이션 넣어보니까 조금 더 부드럽게 동작하는 것 같아서 혹시 넣어보는거 어떨까용??..

2023-02-14 07:02 UTC, llghdud921 commented on FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
> +
너무 좋아요!!!!!

2023-02-14 07:03 UTC, llghdud921 reviewed
선영님 꼼꼼한 피드백 감사드립니다 🙇‍♀️

- 동데이터 코드가 잘못들어가있어서 수정했습니다
- 애니메이션을 적용하였습니다 

중심좌표는 서버에 요청드렸거든요 데이터 내려오는대로 적용하겠습니다 👍

그리고 줌레벨을 더 낮춰볼까요...? 우선 중심좌표랑 마커 뿌려지는 것 보고 Pm이랑 이야기해봐야할것같기도 합니다..ㅠ

2023-02-14 11:21 UTC, seonyoung42 approved these changes
호영님 고생많으셨습니다 👍🏻👍🏻 !!
지도 예뻐요 🥹🥹
아 중심좌표를 알 수 없다면 zoom을 줄여서 해당 동이 한 눈에라도 보이게 하는게 어떨까 싶어서 말씀드렸던거였어요! 중심좌표 받을 수 있다면 지금 딱 좋습니다 👍🏻!!

2023-02-14 11:22 UTC, ungchun commented on FindTown/FindTown/Domain/Constant/MapConstant.swift
> +                                           [124.517393, 39.327518]]
편안하네요.. 👍😄

2023-02-14 11:33 UTC, ungchun approved these changes
호영님..! 고생하셨습니다..!! ㅠㅠㅠㅠ 😀👍

- minZoomLevel 값을 너무 낮춰버리면 mapView.extent 서울 인근으로 카메라 제한했던 영역을 벗어나더라구요.. (그래서 네이버 가이드에서 같이 쓰라고 적어놔둔 것 같습니다..!) 요 값은 적절하게 찍어보면서 수정하면 될 것 같아요!! 😄
- 카메라 줌을 땡길 수 있는 최대값 설정하는 maxZoomLevel도 있습니다..! (높으면 높을수록 더 지도를 자세하게 볼 수 있습니다!) 테스트 해봤을 때 18.0 정도면 적당한 것 같더라구요..!! 한번 넣어보시고 괜찮다면 추가해도 좋을 것 같습니다! 😄
```
mapView.maxZoomLevel = 18.0
```
- MapViewController 안에 isFavoriteCity print 하나 숨어있네요..!!

2023-02-14 12:16 UTC, merged