홈 동네 리스트 불러오는 로직
YAPP-Github/21st-iOS-Team-1-iOS pull request #74
Opened 2023-02-15 07:00 UTC by ungchun

## Motivation
- issue number : #37

## Changes
- 키보드 버그 수정 
- 홈 동네 리스트 불러오기

## Screen Shots
<img width="320" alt="스크린샷 2023-02-15 오후 3 45 36" src="https://user-images.githubusercontent.com/50910456/218952742-6a9261a7-cae8-4952-b71e-1132e2c4d518.png">

## To Reviewers
- 지훈님께서 필터 출력만 고려하시고 처음 접속하거나, 필터를 적용하지 않았을 때 동네 리스트를 불러오는 걸 고려하지 못하셔서 우선 페이지네이션 없이 27개 동이 한번에 내려옵니다..!! 😅
- 네트워크 에러 났을 때 더미데이터? TownTableMockData를 사용해서 동네 1개를 보여주게 했는데요.. 동네를 추가한다거나 더 좋은 방법이 있으면 조언 부탁드립니다.. 😢
- FavoriteViewModel에 있는 townModelTest은 선영님이 추후에 작업진행하시면 삭제하면 됩니다! (우선 에러 안나게 남겨뒀어요!!)
- CityCode 호영님이 수정하신 부분을 제가 pull 받고 작업을 한게 아니라서 merge할 때 신경써서 merge 하겠습니다! 그리고 328, 333, 206 CityCode가 없어서 추가했습니다!! 😀
- 작업하다 자잘한 UI 수정이나 네이밍 수정도 같이 올렸습니다.. 😅

2023-02-15 08:34 UTC, seonyoung42 reviewed
성훈님 고생많으셨습니다 👍🏻 !!
+ 네트워크 에러 났을 때 MockData가 나오면 동네 소개나 동네 지도를 누를 수 있게 되니까.. 아예 아무 동도 나오지 않거나 네트워크 에러 메세지가 떠야하지 않을까요??.. 이 부분은 다같이 얘기해봐야하지 않나 싶어요 🥲

2023-02-15 08:34 UTC, seonyoung42 commented on FindTown/FindTownUI/Sources/FindTownUI/Extensions/UIButton+Extension.swift
>  }
여기 padding 값을 매개변수로 전달 할 수 있도록 하는건 어떨까요?!

2023-02-15 08:35 UTC, seonyoung42 approved these changes

2023-02-15 15:50 UTC, llghdud921 requested changes
성훈님 고생많으셨습니다!


- 인프라, 교통 선택 시에 다시 바텀시트를 열게되면 이전에 선택되었던 값이 사라지더라구요 개선이 필요할 것 같습니다!

- 아래처럼 필터 결과가 없는 경우 레이아웃이 달라지는데 개선 부탁드릴게요!
![Simulator Screen Recording - iPhone 13 Pro Max - 2023-02-16 at 00 48 19](https://user-images.githubusercontent.com/40068674/219078704-7f997113-918f-42e8-a71f-95d2257f3fb7.gif)

- 이미지 뷰가 눌리는것같아요 이미지뷰가 아닌 텍스트로 넣으면 안깨지더라구요! 확인 부탁드릴게요~
![Uploading 스크린샷 2023-02-16 오전 12.49.23.png…]()

- 현재 home 내에 selectCounty가 있는데 외부로 빼도 될 것 같구요 네이밍이 맞지 않는 것 같아요 개선 부탁드립니다~!

2023-02-15 15:50 UTC, llghdud921 commented on FindTown/FindTown/Data/DataMapping/Reponse/TownFilterResponseDTO.swift
> +            let tableModel = TownTableModel(objectId: townInformation.objectId, county: county, countyIcon: countyIcon, wishTown: wishTown, safetyRate: safetyRate, townIntroduction: townIntroduction)
이거 줄바꿈으로 코드 정리를 해볼까요!

2023-02-16 07:07 UTC, seonyoung42 approved these changes
성훈님 고생많으셨습니다 👍🏻!
serviceMapView도 잘 되더라구요 !! 
한 가지 건의(ㅎㅎ;;) 드리고 싶은게 있는데요! 
인프라, 교통을 선택하고 다시 선택하려고할 때 이전에 선택했던 항목들은 눌려진 상태로 보여야 하지 않을까 싶어서요 한번 검토 부탁드립니다 ~~!

2023-02-16 07:07 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableFooterView.swift
> +
오옹 footerView로 넣으셨네요 !! 넘 좋아요 👍🏻👍🏻 !!

2023-02-16 07:07 UTC, seonyoung42 commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
>          ])
성훈님 혹시 호영님께서 말씀하신 부분이 개선이 됐을까요?! 
보니까 tableViewHeaderView의 높이가 고정되어 있어 발생한 이슈 같아요! heightAnchor를 지우고 townListTitleAndSafeScoreView에 topAnchor를 넣어주니까 예쁘게 나오더라구요. 도움이 될까 해서 남겨봅니당

2023-02-16 09:12 UTC, ungchun commented on FindTown/FindTown/Data/DataMapping/Reponse/TownFilterResponseDTO.swift
> +            let tableModel = TownTableModel(objectId: townInformation.objectId, county: county, countyIcon: countyIcon, wishTown: wishTown, safetyRate: safetyRate, townIntroduction: townIntroduction)
수정했습니당..!! 😅

2023-02-16 09:21 UTC, ungchun commented
> 인프라, 교통 선택 시에 다시 바텀시트를 열게되면 이전에 선택되었던 값이 사라지더라구요 개선이 필요할 것 같습니다!

- 이 부분 말씀해주신대로 수정했습니다..!! 😀

> 아래처럼 필터 결과가 없는 경우 레이아웃이 달라지는데 개선 부탁드릴게요!

- 이 부분도 레이아웃이 어색하지 않게 수정했습니다!! 피그마상에는 동네 갯수가 안나오는데 디자이너님이랑 이야기해서 0개 동네로 출력하기로 했어요!! 😀

> 이미지 뷰가 눌리는것같아요 이미지뷰가 아닌 텍스트로 넣으면 안깨지더라구요! 확인 부탁드릴게요~

- 앞으로 커스텀 이미지를 넣으면 텍스트로 넣어야겠어요.. 👍

> 현재 home 내에 SearchCounty가 있는데 외부로 빼도 될 것 같구요 SearchCounty 네이밍이 맞지 않는 것 같아요 개선 부탁드립니다~!

- 보니까 외부로 빼는게 맞는 것 같아서 외부로 빼버렸습니다..!! 👍😀

- 현재 서버에 인프라 관련해서 데이터가 안들어가있어서 데이터가 정상적으로 출력이 안됩니다.. 참고해주세요!!

- 네트워크 에러 발생했을 시 다시 시도하기 버튼이 있는데요.. 시간을 꽤 들였는데도 무슨 이유에선지 버튼 클릭이 안먹히더라구요.. 머지를 위해 우선 제거를 했고 계속 살펴보겠습니당..!! 😢

2023-02-16 09:22 UTC, ungchun commented on FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
>          ])
우선 작성해두신건 다 처리를 했습니다!! 😀

2023-02-16 15:41 UTC, llghdud921 approved these changes
👍

2023-02-16 18:09 UTC, merged