동네소개 네트워크 연결
YAPP-Github/21st-iOS-Team-1-iOS pull request #80
Opened 2023-02-18 03:16 UTC by seonyoung42

## Motivation
- issue number : #79 

## Changes
- 동네소개 네트워크 연결
- 찜 -> 동네소개 화면 전환 
- 찜 townTableViewDelegate 적용

## Screen Shots
- 

## To Reviewers
- isAnonymous pr 머지되면 둘러보기인 경우(accessToken = nil) 적용해서 수정예정입니다 !

2023-02-18 05:50 UTC, ungchun commented on FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewController.swift
> +                cell.cityCode = item.objectId
setupCell 안으로 빼는건 어떠세요?! 😀

2023-02-18 05:57 UTC, ungchun commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/TownRank/TownRankView.swift
> -        case .livable:
data.0 data.1 알아보기 힘든 것 같아요..!! 🤔
이름을 지정해주는게 어떨까용..?

2023-02-18 06:08 UTC, ungchun commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
> -    var safety = "안심보안관 활동지"
TownRankData의 위치가 TownIntroViewModel 보다는 Entities 쪽으로 빼는게 어떨까요?
그리고 Encodable을 붙이신 이유가 있을까요..? 🤔

2023-02-18 06:14 UTC, ungchun commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
> +                                trafficRank: data.trafficRate,
test 네이밍 수정 부탁드려요! 😄

2023-02-18 06:49 UTC, ungchun requested changes
선영님! 고생하셨습니다!! 😀

- townIntroTask의 error popup에 확인버튼을 누르면 popup만 dismiss되는게 아니라 페이지가 뒤로가는 로직(pop)을 추가하면 좋겠어요!! 😀 
- 현재 Intro 라는 네이밍으로 되어있는데 Introduce로 수정하는건 어떠신가요? 저도 info로 했다가 전부 information으로 수정했거든요..! 😄

2023-02-18 13:02 UTC, llghdud921 requested changes
선영님! 동네 소개 아주 잘되네요 👍

그리고 return을 사용하신 네이밍이 종종 보이는데.. return보다 convert...?를 쓰는것이 더 좋아보이는 것 같아요 한번 고려부탁드립니당
성훈님이 남겨주신 코멘트와 저도 동일한 생각이 많아서 조금 더 개선이 되면 좋을 것 같습니다!!

2023-02-18 13:02 UTC, llghdud921 commented on FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewModel.swift
> +            .subscribe(onNext: { cityCode in
[weak self] 없는 바인딩이 종종 보이네요!

2023-02-18 13:02 UTC, llghdud921 commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
> +    func returnTownMoodData(_ townMoodStringArray: [String]) -> [TownMood] {
이건 viewModel에서 가공하는 것보다 엔터티를 만들고 TownIntroDTO -> Entity 로 변환할 때 가공하는 것이 더 좋아보입니다!

2023-02-18 13:02 UTC, llghdud921 commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
> +    func returnTownRankData(data: TownIntroDTO ) -> [(TownRank,Any)] {
이 메서드가 수정될수도 있지만 파라미터명을 data라고 쓰기보다 townIntroData 이렇게 네이밍하는 것이 훨씬 알아보기 좋을 것 같네용

2023-02-18 13:02 UTC, llghdud921 commented on FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
>  struct TownRankData: Encodable {
저도 이건 Entity로 빼야한다고 생각해요!

2023-02-19 08:53 UTC, seonyoung42 commented
꼼꼼한 피드백 다들 넘 감사합니다 🥹🥹
피드백 주신 부분들 모두 제가 놓치고 있던 부분이라 다 반영해서 개선했구요
TownRankData 구조체는 TownRank 타입으로 반환하기 위해 사용되는 타입이라 Entity로 따로 빼지 않고 TownRank 파일 내에 넣었습니다!

2023-02-19 10:20 UTC, ungchun requested changes
선영님! 고생하셨습니다..! 😀

현재 상도1동(305)를 보면 "산책하기 좋은" 이라고 1개가 찍혀있는데  

![스크린샷 2023-02-19 오후 7 14 38](https://user-images.githubusercontent.com/50910456/219941813-1760c131-1af9-46c4-8daa-865356d2da01.png)

![스크린샷 2023-02-19 오후 7 14 24](https://user-images.githubusercontent.com/50910456/219941867-809280ce-d1fc-438c-a14c-872060758f60.png)

앱에서는 아무것도 보이지 않습니다..! 

![스크린샷 2023-02-19 오후 7 14 31](https://user-images.githubusercontent.com/50910456/219941877-2206e8a1-8556-4305-98d4-33c88d6365c3.png)

다른 동네에서 "산책하기 좋은"는 제대로 나와요..! 동네분위기가 1개일 경우 안나오는 것 같은데.. 한번 확인 부탁드릴게요..!! 😄

2023-02-19 11:09 UTC, seonyoung42 commented
> 
확인해보니까 UICollectionView.automaticSize 로 셀 크기를 설정했을 때 발생하는 버그더라구요 🥹 임의 사이즈 설정해서 해결했습니다! 알려주셔서 감사해요 !!

2023-02-19 12:40 UTC, llghdud921 approved these changes
선영님 너무 좋네요 😀
고생많으셨습니다~~!

2023-02-19 12:42 UTC, ungchun approved these changes
고생하셨습니다!! 👍😀

2023-02-19 14:05 UTC, merged