찜 목록 조회, 찜 등록 네트워크 구현
YAPP-Github/21st-iOS-Team-1-iOS pull request #85
Opened 2023-02-19 18:09 UTC by seonyoung42

## Motivation
- issue number : #75 

## Changes
- 찜 목록 불러오기 
- 찜 등록, 해제 
- 홈, 검색 화면의 동네소개, 찜 기능 추가

## Screen Shots
- ![Simulator Screen Shot - iPhone 13 - 2023-02-20 at 03 04 00](https://user-images.githubusercontent.com/77603632/219966490-35259bc3-f5f4-43d5-bc30-24ec222e3d4a.png)

## To Reviewers
- 둘러보기인 경우에도 홈, 검색화면에서 찜 버튼이 노출되고 있어서 이 경우에 대한 화면 여쭤봐야할 것 같아요!
- 홈, 검색 화면의 townTableViewCell 에 찜 여부 반영이 안되고 있는 것 같아요 한 번 확인 부탁드리겠습니다
- TownTableViewCell 내의 disposeBag = DisposeBag() 일단 주석 처리했습니다.. 이게 있으니까 찜 메서드 호출 자체가 안돼요... ㅠ

2023-02-20 00:34 UTC, llghdud921 requested changes
선영님 코드 깔끔하네요 👍👍

- 둘러보기 경우 찜버튼을 누르면 회원가입 유도 팝업을 띄우는것도 생각하고 있어요.. 기획쪽에 이야기 해보겠습니당

> TownTableViewCell 내의 disposeBag = DisposeBag() 일단 주석 처리했습니다.. 이게 있으니까 delegate 메서드 자체가 호출이 안돼요..

저도 그랬던 것 같습니다ㅎㅎ 아예 지원도 좋을 것 같아요

- 찜 등록 해제가 하나의 api네요.. 이거 호환성에 문제가 발생할 수 있을것같은데 서버에 이야기 해서 찜등록 api, 찜 해제 api로 분리해야할 것 같습니다

2023-02-20 04:56 UTC, ungchun requested changes
선영님! 고생하셨습니다!! 👍

> 홈, 검색 화면의 townTableViewCell 에 찜 여부 반영이 안되고 있는 것 같아요 한 번 확인 부탁드리겠습니다

- 이 부분 보내드린 코드 넣으시고 테스트 부탁드릴게요..!! 😅

<img width="528" alt="스크린샷 2023-02-20 오후 1 38 37" src="https://user-images.githubusercontent.com/50910456/220010968-db416b76-1ff5-4ba9-8263-b75ff40fcf3d.png">

- 제가 어제 밤에 디벨롭에 요 코드를 바로 푸시를 했는데요.. 선영님도 추가하셨더라구요!! 머지하실 때 제 코드는 지워주시면 될 것 같습니다!!

<img width="272" alt="스크린샷 2023-02-20 오후 1 41 29" src="https://user-images.githubusercontent.com/50910456/220011122-755d6957-cb39-4edf-8b39-0fc89f856a9a.png">

- 토스트가 빠져있는 것 같아요!! 😀

![Simulator Screen Recording - iPhone 14 - 2023-02-20 at 13 53 42](https://user-images.githubusercontent.com/50910456/220012461-9133f32d-341b-4731-a33e-128907c5d6e2.gif)

- 이게 찜에서 해제를 하고 유저정보를 불러오면 찜 정보가 업데이트가 되지 않습니다.. 서버쪽에서 연결을 안해놓은건지 잘 모르겠네요.. 이거 말고도 홈, 검색 결과, 찜 화면 에서 왔다 갔다 해보면 호환이 안되는 부분이 많습니다.. 😢 한번 체크 부탁드릴게요!!

2023-02-21 04:40 UTC, seonyoung42 commented
서버에서 찜 데이터 이슈 수정해주셨습니다 🥹🥹🥳
pr이 너무 커질 것 같아 일단 여기까지만 수정해서 올릴게요!
추가된 부분이 좀 있어서 목록으로 정리해놓을게요

+ 찜 
	- 찜 목록에서 해제시 토스트 팝업
+ 홈, 검색
	- 익명인 경우 찜 버튼 누르면 팝업 뜨도록
+ 동네 소개
	- 익명인 경우 accessToken
	- 익명인 경우 찜 버튼 제거
+ 동네 지도
	- 익명인 경우 찜 버튼 제거
+ AlertSuccessCancel팝업
 	- 마진 수정

2023-02-21 08:18 UTC, llghdud921 approved these changes

2023-02-21 08:25 UTC, ungchun approved these changes

2023-02-21 09:31 UTC, merged